// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: update_sym
 *
 * Args:
 *     state: Matrix71
 *     covariance: Matrix77
 *     measurement: Matrix31
 *     measurement_noise: Matrix33
 *
 * Outputs:
 *     new_state: Matrix71
 *     new_covariance: Matrix77
 */
template <typename Scalar>
void Update(const Eigen::Matrix<Scalar, 7, 1>& state, const Eigen::Matrix<Scalar, 7, 7>& covariance,
            const Eigen::Matrix<Scalar, 3, 1>& measurement,
            const Eigen::Matrix<Scalar, 3, 3>& measurement_noise,
            Eigen::Matrix<Scalar, 7, 1>* const new_state = nullptr,
            Eigen::Matrix<Scalar, 7, 7>* const new_covariance = nullptr) {
  // Total ops: 1720

  // Input arrays

  // Intermediate terms (189)
  const Scalar _tmp0 = 2 * state(0, 0);
  const Scalar _tmp1 = -_tmp0 * covariance(2, 2);
  const Scalar _tmp2 = 2 * state(1, 0);
  const Scalar _tmp3 = 2 * state(3, 0);
  const Scalar _tmp4 = -_tmp3 * covariance(2, 1);
  const Scalar _tmp5 = 2 * state(2, 0);
  const Scalar _tmp6 = _tmp1 - _tmp2 * covariance(2, 3) + _tmp4 - _tmp5 * covariance(2, 0);
  const Scalar _tmp7 = -_tmp5 * covariance(0, 0);
  const Scalar _tmp8 = _tmp2 * covariance(3, 0);
  const Scalar _tmp9 = -_tmp0 * covariance(2, 0) - _tmp3 * covariance(1, 0) + _tmp7 - _tmp8;
  const Scalar _tmp10 = -_tmp5 * covariance(0, 3);
  const Scalar _tmp11 = -_tmp2 * covariance(3, 3);
  const Scalar _tmp12 = -_tmp0 * covariance(2, 3) + _tmp10 + _tmp11 - _tmp3 * covariance(1, 3);
  const Scalar _tmp13 = -_tmp3 * covariance(1, 2);
  const Scalar _tmp14 = _tmp1 + _tmp13 - _tmp2 * covariance(3, 2) - _tmp5 * covariance(0, 2);
  const Scalar _tmp15 = -_tmp3 * covariance(1, 1);
  const Scalar _tmp16 = _tmp0 * covariance(2, 1);
  const Scalar _tmp17 = _tmp15 - _tmp16 - _tmp2 * covariance(3, 1) - _tmp5 * covariance(0, 1);
  const Scalar _tmp18 = Scalar(1.0) / (-_tmp0 * _tmp14 - _tmp12 * _tmp2 - _tmp17 * _tmp3 -
                                       _tmp5 * _tmp9 + measurement_noise(0, 0));
  const Scalar _tmp19 = 4 * state(1, 0);
  const Scalar _tmp20 = 4 * state(2, 0);
  const Scalar _tmp21 = 2 * _tmp19 * covariance(1, 0) + 2 * _tmp20 * covariance(2, 0);
  const Scalar _tmp22 = 2 * _tmp19 * covariance(1, 3) + 2 * _tmp20 * covariance(2, 3);
  const Scalar _tmp23 = _tmp19 * covariance(1, 1);
  const Scalar _tmp24 = _tmp20 * covariance(2, 1) + _tmp23;
  const Scalar _tmp25 = _tmp20 * covariance(2, 2);
  const Scalar _tmp26 = _tmp19 * covariance(1, 2) + _tmp25;
  const Scalar _tmp27 = _tmp18 * (-_tmp0 * _tmp26 - _tmp21 * state(2, 0) - _tmp22 * state(1, 0) -
                                  _tmp24 * _tmp3 + measurement_noise(2, 0));
  const Scalar _tmp28 = _tmp2 * covariance(0, 0);
  const Scalar _tmp29 = -_tmp5 * covariance(3, 0);
  const Scalar _tmp30 = _tmp0 * covariance(1, 0) + _tmp28 + _tmp29 - _tmp3 * covariance(2, 0);
  const Scalar _tmp31 = _tmp2 * covariance(0, 3);
  const Scalar _tmp32 = -_tmp5 * covariance(3, 3);
  const Scalar _tmp33 = _tmp0 * covariance(1, 3) - _tmp3 * covariance(2, 3) + _tmp31 + _tmp32;
  const Scalar _tmp34 = _tmp0 * covariance(1, 2);
  const Scalar _tmp35 = -_tmp3 * covariance(2, 2);
  const Scalar _tmp36 = _tmp2 * covariance(0, 2) + _tmp34 + _tmp35 - _tmp5 * covariance(3, 2);
  const Scalar _tmp37 = _tmp0 * covariance(1, 1);
  const Scalar _tmp38 = _tmp2 * covariance(0, 1) + _tmp37 + _tmp4 - _tmp5 * covariance(3, 1);
  const Scalar _tmp39 = _tmp18 * (-_tmp0 * _tmp36 - _tmp2 * _tmp33 - _tmp3 * _tmp38 -
                                  _tmp30 * _tmp5 + measurement_noise(1, 0));
  const Scalar _tmp40 =
      _tmp0 * _tmp17 - _tmp12 * _tmp5 - _tmp14 * _tmp3 + _tmp2 * _tmp9 + measurement_noise(0, 1);
  const Scalar _tmp41 = Scalar(1.0) / (_tmp0 * _tmp38 + _tmp2 * _tmp30 - _tmp3 * _tmp36 -
                                       _tmp33 * _tmp5 - _tmp39 * _tmp40 + measurement_noise(1, 1));
  const Scalar _tmp42 = _tmp41 * (_tmp0 * _tmp24 + _tmp21 * state(1, 0) - _tmp22 * state(2, 0) -
                                  _tmp26 * _tmp3 - _tmp27 * _tmp40 + measurement_noise(2, 1));
  const Scalar _tmp43 = -_tmp27 + _tmp39 * _tmp42;
  const Scalar _tmp44 = _tmp14 * _tmp20 + _tmp17 * _tmp19 + measurement_noise(0, 2);
  const Scalar _tmp45 =
      _tmp19 * _tmp38 + _tmp20 * _tmp36 - _tmp39 * _tmp44 + measurement_noise(1, 2);
  const Scalar _tmp46 = Scalar(1.0) / (_tmp19 * _tmp24 + _tmp20 * _tmp26 - _tmp27 * _tmp44 -
                                       _tmp42 * _tmp45 + measurement_noise(2, 2));
  const Scalar _tmp47 = _tmp44 * _tmp46;
  const Scalar _tmp48 = _tmp45 * _tmp46;
  const Scalar _tmp49 = -_tmp39 - _tmp43 * _tmp48;
  const Scalar _tmp50 = _tmp40 * _tmp41;
  const Scalar _tmp51 = _tmp18 * (-_tmp43 * _tmp47 - _tmp49 * _tmp50 + 1);
  const Scalar _tmp52 = _tmp16 + _tmp2 * covariance(2, 0) + _tmp35 - _tmp5 * covariance(2, 3);
  const Scalar _tmp53 = _tmp41 * _tmp49;
  const Scalar _tmp54 = _tmp46 * (_tmp19 * covariance(2, 1) + _tmp25);
  const Scalar _tmp55 = _tmp43 * _tmp54 + _tmp51 * _tmp6 + _tmp52 * _tmp53;
  const Scalar _tmp56 = _tmp0 * state(2, 0) + _tmp3 * state(1, 0) + measurement(0, 0);
  const Scalar _tmp57 = _tmp41 * _tmp48;
  const Scalar _tmp58 = -_tmp47 + _tmp48 * _tmp50;
  const Scalar _tmp59 = _tmp18 * _tmp58;
  const Scalar _tmp60 = -_tmp52 * _tmp57 + _tmp54 + _tmp59 * _tmp6;
  const Scalar _tmp61 = measurement(2, 0) - 2 * std::pow(state(1, 0), Scalar(2)) -
                        2 * std::pow(state(2, 0), Scalar(2)) + 1;
  const Scalar _tmp62 = _tmp42 * _tmp48 + 1;
  const Scalar _tmp63 = _tmp42 * _tmp47 - _tmp50 * _tmp62;
  const Scalar _tmp64 = _tmp18 * _tmp63;
  const Scalar _tmp65 = _tmp41 * _tmp62;
  const Scalar _tmp66 = -_tmp42 * _tmp54 + _tmp52 * _tmp65 + _tmp6 * _tmp64;
  const Scalar _tmp67 = -_tmp0 * state(1, 0) + _tmp3 * state(2, 0) + measurement(1, 0);
  const Scalar _tmp68 = _tmp55 * _tmp56 + _tmp60 * _tmp61 + _tmp66 * _tmp67 + state(2, 0);
  const Scalar _tmp69 =
      _tmp41 * (_tmp13 + _tmp2 * covariance(1, 0) + _tmp37 - _tmp5 * covariance(1, 3));
  const Scalar _tmp70 = _tmp46 * (_tmp20 * covariance(1, 2) + _tmp23);
  const Scalar _tmp71 = _tmp15 - _tmp2 * covariance(1, 3) - _tmp34 - _tmp5 * covariance(1, 0);
  const Scalar _tmp72 = -_tmp42 * _tmp70 + _tmp62 * _tmp69 + _tmp64 * _tmp71;
  const Scalar _tmp73 = _tmp43 * _tmp70 + _tmp49 * _tmp69 + _tmp51 * _tmp71;
  const Scalar _tmp74 = -_tmp48 * _tmp69 + _tmp59 * _tmp71 + _tmp70;
  const Scalar _tmp75 = _tmp56 * _tmp73 + _tmp61 * _tmp74 + _tmp67 * _tmp72 + state(1, 0);
  const Scalar _tmp76 = _tmp46 * (_tmp19 * covariance(3, 1) + _tmp20 * covariance(3, 2));
  const Scalar _tmp77 = _tmp0 * covariance(3, 1) - _tmp3 * covariance(3, 2) + _tmp32 + _tmp8;
  const Scalar _tmp78 = -_tmp0 * covariance(3, 2) + _tmp11 + _tmp29 - _tmp3 * covariance(3, 1);
  const Scalar _tmp79 = _tmp18 * _tmp78;
  const Scalar _tmp80 = -_tmp42 * _tmp76 + _tmp63 * _tmp79 + _tmp65 * _tmp77;
  const Scalar _tmp81 = -_tmp57 * _tmp77 + _tmp58 * _tmp79 + _tmp76;
  const Scalar _tmp82 = _tmp43 * _tmp76 + _tmp51 * _tmp78 + _tmp53 * _tmp77;
  const Scalar _tmp83 = _tmp56 * _tmp82 + _tmp61 * _tmp81 + _tmp67 * _tmp80 + state(3, 0);
  const Scalar _tmp84 = -_tmp0 * covariance(0, 2) - _tmp3 * covariance(0, 1) - _tmp31 + _tmp7;
  const Scalar _tmp85 = _tmp46 * (_tmp19 * covariance(0, 1) + _tmp20 * covariance(0, 2));
  const Scalar _tmp86 = _tmp0 * covariance(0, 1) + _tmp10 + _tmp28 - _tmp3 * covariance(0, 2);
  const Scalar _tmp87 = _tmp43 * _tmp85 + _tmp51 * _tmp84 + _tmp53 * _tmp86;
  const Scalar _tmp88 = -_tmp42 * _tmp85 + _tmp64 * _tmp84 + _tmp65 * _tmp86;
  const Scalar _tmp89 = -_tmp57 * _tmp86 + _tmp59 * _tmp84 + _tmp85;
  const Scalar _tmp90 = _tmp56 * _tmp87 + _tmp61 * _tmp89 + _tmp67 * _tmp88 + state(0, 0);
  const Scalar _tmp91 = std::pow(Scalar(std::pow(_tmp68, Scalar(2)) + std::pow(_tmp75, Scalar(2)) +
                                        std::pow(_tmp83, Scalar(2)) + std::pow(_tmp90, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp92 = _tmp46 * (_tmp19 * covariance(4, 1) + _tmp20 * covariance(4, 2));
  const Scalar _tmp93 = -_tmp0 * covariance(4, 2) - _tmp2 * covariance(4, 3) -
                        _tmp3 * covariance(4, 1) - _tmp5 * covariance(4, 0);
  const Scalar _tmp94 = _tmp0 * covariance(4, 1) + _tmp2 * covariance(4, 0) -
                        _tmp3 * covariance(4, 2) - _tmp5 * covariance(4, 3);
  const Scalar _tmp95 = -_tmp57 * _tmp94 + _tmp59 * _tmp93 + _tmp92;
  const Scalar _tmp96 = -_tmp42 * _tmp92 + _tmp64 * _tmp93 + _tmp65 * _tmp94;
  const Scalar _tmp97 = _tmp43 * _tmp92 + _tmp51 * _tmp93 + _tmp53 * _tmp94;
  const Scalar _tmp98 = _tmp46 * (_tmp19 * covariance(5, 1) + _tmp20 * covariance(5, 2));
  const Scalar _tmp99 = _tmp0 * covariance(5, 1) + _tmp2 * covariance(5, 0) -
                        _tmp3 * covariance(5, 2) - _tmp5 * covariance(5, 3);
  const Scalar _tmp100 = -_tmp0 * covariance(5, 2) - _tmp2 * covariance(5, 3) -
                         _tmp3 * covariance(5, 1) - _tmp5 * covariance(5, 0);
  const Scalar _tmp101 = _tmp100 * _tmp64 - _tmp42 * _tmp98 + _tmp65 * _tmp99;
  const Scalar _tmp102 = _tmp100 * _tmp59 - _tmp57 * _tmp99 + _tmp98;
  const Scalar _tmp103 = _tmp100 * _tmp51 + _tmp43 * _tmp98 + _tmp53 * _tmp99;
  const Scalar _tmp104 = -_tmp0 * covariance(6, 2) - _tmp2 * covariance(6, 3) -
                         _tmp3 * covariance(6, 1) - _tmp5 * covariance(6, 0);
  const Scalar _tmp105 = _tmp0 * covariance(6, 1) + _tmp2 * covariance(6, 0) -
                         _tmp3 * covariance(6, 2) - _tmp5 * covariance(6, 3);
  const Scalar _tmp106 = _tmp46 * (_tmp19 * covariance(6, 1) + _tmp20 * covariance(6, 2));
  const Scalar _tmp107 = _tmp104 * _tmp51 + _tmp105 * _tmp53 + _tmp106 * _tmp43;
  const Scalar _tmp108 = _tmp104 * _tmp64 + _tmp105 * _tmp65 - _tmp106 * _tmp42;
  const Scalar _tmp109 = _tmp104 * _tmp59 - _tmp105 * _tmp57 + _tmp106;
  const Scalar _tmp110 = _tmp87 * measurement_noise(0, 1) + _tmp88 * measurement_noise(1, 1) +
                         _tmp89 * measurement_noise(2, 1);
  const Scalar _tmp111 = _tmp87 * measurement_noise(0, 2) + _tmp88 * measurement_noise(1, 2) +
                         _tmp89 * measurement_noise(2, 2);
  const Scalar _tmp112 = -_tmp2 * _tmp87 - _tmp5 * _tmp88;
  const Scalar _tmp113 = _tmp0 * _tmp88 + _tmp19 * _tmp89 - _tmp3 * _tmp87;
  const Scalar _tmp114 = -_tmp0 * _tmp87 + _tmp20 * _tmp89 - _tmp3 * _tmp88;
  const Scalar _tmp115 = -_tmp2 * _tmp88 + _tmp5 * _tmp87 + 1;
  const Scalar _tmp116 = -_tmp112 * covariance(3, 3) - _tmp113 * covariance(1, 3) -
                         _tmp114 * covariance(2, 3) + _tmp115 * covariance(0, 3);
  const Scalar _tmp117 = _tmp87 * measurement_noise(0, 0) + _tmp88 * measurement_noise(1, 0) +
                         _tmp89 * measurement_noise(2, 0);
  const Scalar _tmp118 = -_tmp112 * covariance(3, 0) - _tmp113 * covariance(1, 0) -
                         _tmp114 * covariance(2, 0) + _tmp115 * covariance(0, 0);
  const Scalar _tmp119 = -_tmp112 * covariance(3, 1) - _tmp113 * covariance(1, 1) -
                         _tmp114 * covariance(2, 1) + _tmp115 * covariance(0, 1);
  const Scalar _tmp120 = -_tmp112 * covariance(3, 2) - _tmp113 * covariance(1, 2) -
                         _tmp114 * covariance(2, 2) + _tmp115 * covariance(0, 2);
  const Scalar _tmp121 = _tmp72 * measurement_noise(1, 1) + _tmp73 * measurement_noise(0, 1) +
                         _tmp74 * measurement_noise(2, 1);
  const Scalar _tmp122 = _tmp72 * measurement_noise(1, 2) + _tmp73 * measurement_noise(0, 2) +
                         _tmp74 * measurement_noise(2, 2);
  const Scalar _tmp123 = -_tmp0 * _tmp73 + _tmp20 * _tmp74 - _tmp3 * _tmp72;
  const Scalar _tmp124 = -_tmp0 * _tmp72 - _tmp19 * _tmp74 + _tmp3 * _tmp73 + 1;
  const Scalar _tmp125 = -_tmp2 * _tmp73 - _tmp5 * _tmp72;
  const Scalar _tmp126 = _tmp2 * _tmp72 - _tmp5 * _tmp73;
  const Scalar _tmp127 = -_tmp123 * covariance(2, 0) + _tmp124 * covariance(1, 0) -
                         _tmp125 * covariance(3, 0) - _tmp126 * covariance(0, 0);
  const Scalar _tmp128 = -_tmp123 * covariance(2, 2) + _tmp124 * covariance(1, 2) -
                         _tmp125 * covariance(3, 2) - _tmp126 * covariance(0, 2);
  const Scalar _tmp129 = -_tmp123 * covariance(2, 1) + _tmp124 * covariance(1, 1) -
                         _tmp125 * covariance(3, 1) - _tmp126 * covariance(0, 1);
  const Scalar _tmp130 = -_tmp123 * covariance(2, 3) + _tmp124 * covariance(1, 3) -
                         _tmp125 * covariance(3, 3) - _tmp126 * covariance(0, 3);
  const Scalar _tmp131 = _tmp72 * measurement_noise(1, 0) + _tmp73 * measurement_noise(0, 0) +
                         _tmp74 * measurement_noise(2, 0);
  const Scalar _tmp132 = 2 * _tmp55;
  const Scalar _tmp133 = -_tmp132 * state(1, 0) - _tmp5 * _tmp66;
  const Scalar _tmp134 = -_tmp132 * state(2, 0) + _tmp2 * _tmp66;
  const Scalar _tmp135 = _tmp132 * state(0, 0) - _tmp20 * _tmp60 + _tmp3 * _tmp66 + 1;
  const Scalar _tmp136 = _tmp0 * _tmp66 - _tmp132 * state(3, 0) + _tmp19 * _tmp60;
  const Scalar _tmp137 = -_tmp133 * covariance(3, 3) - _tmp134 * covariance(0, 3) +
                         _tmp135 * covariance(2, 3) - _tmp136 * covariance(1, 3);
  const Scalar _tmp138 = _tmp55 * measurement_noise(0, 2) + _tmp60 * measurement_noise(2, 2) +
                         _tmp66 * measurement_noise(1, 2);
  const Scalar _tmp139 = -_tmp133 * covariance(3, 0) - _tmp134 * covariance(0, 0) +
                         _tmp135 * covariance(2, 0) - _tmp136 * covariance(1, 0);
  const Scalar _tmp140 = -_tmp133 * covariance(3, 2) - _tmp134 * covariance(0, 2) +
                         _tmp135 * covariance(2, 2) - _tmp136 * covariance(1, 2);
  const Scalar _tmp141 = _tmp55 * measurement_noise(0, 1) + _tmp60 * measurement_noise(2, 1) +
                         _tmp66 * measurement_noise(1, 1);
  const Scalar _tmp142 = -_tmp133 * covariance(3, 1) - _tmp134 * covariance(0, 1) +
                         _tmp135 * covariance(2, 1) - _tmp136 * covariance(1, 1);
  const Scalar _tmp143 = _tmp55 * measurement_noise(0, 0) + _tmp60 * measurement_noise(2, 0) +
                         _tmp66 * measurement_noise(1, 0);
  const Scalar _tmp144 = _tmp80 * measurement_noise(1, 0) + _tmp81 * measurement_noise(2, 0) +
                         _tmp82 * measurement_noise(0, 0);
  const Scalar _tmp145 = _tmp80 * measurement_noise(1, 1) + _tmp81 * measurement_noise(2, 1) +
                         _tmp82 * measurement_noise(0, 1);
  const Scalar _tmp146 = _tmp2 * _tmp82 + _tmp5 * _tmp80 + 1;
  const Scalar _tmp147 = _tmp2 * _tmp80 - _tmp5 * _tmp82;
  const Scalar _tmp148 = -_tmp0 * _tmp82 + _tmp20 * _tmp81 - _tmp3 * _tmp80;
  const Scalar _tmp149 = _tmp0 * _tmp80 + _tmp19 * _tmp81 - _tmp3 * _tmp82;
  const Scalar _tmp150 = _tmp146 * covariance(3, 3) - _tmp147 * covariance(0, 3) -
                         _tmp148 * covariance(2, 3) - _tmp149 * covariance(1, 3);
  const Scalar _tmp151 = _tmp146 * covariance(3, 2) - _tmp147 * covariance(0, 2) -
                         _tmp148 * covariance(2, 2) - _tmp149 * covariance(1, 2);
  const Scalar _tmp152 = _tmp146 * covariance(3, 1) - _tmp147 * covariance(0, 1) -
                         _tmp148 * covariance(2, 1) - _tmp149 * covariance(1, 1);
  const Scalar _tmp153 = _tmp80 * measurement_noise(1, 2) + _tmp81 * measurement_noise(2, 2) +
                         _tmp82 * measurement_noise(0, 2);
  const Scalar _tmp154 = _tmp146 * covariance(3, 0) - _tmp147 * covariance(0, 0) -
                         _tmp148 * covariance(2, 0) - _tmp149 * covariance(1, 0);
  const Scalar _tmp155 = -_tmp0 * _tmp97 + _tmp20 * _tmp95 - _tmp3 * _tmp96;
  const Scalar _tmp156 = _tmp0 * _tmp96 + _tmp19 * _tmp95 - _tmp3 * _tmp97;
  const Scalar _tmp157 = -_tmp2 * _tmp97 - _tmp5 * _tmp96;
  const Scalar _tmp158 = _tmp2 * _tmp96 - _tmp5 * _tmp97;
  const Scalar _tmp159 = -_tmp155 * covariance(2, 0) - _tmp156 * covariance(1, 0) -
                         _tmp157 * covariance(3, 0) - _tmp158 * covariance(0, 0) + covariance(4, 0);
  const Scalar _tmp160 = _tmp95 * measurement_noise(2, 1) + _tmp96 * measurement_noise(1, 1) +
                         _tmp97 * measurement_noise(0, 1);
  const Scalar _tmp161 = -_tmp155 * covariance(2, 3) - _tmp156 * covariance(1, 3) -
                         _tmp157 * covariance(3, 3) - _tmp158 * covariance(0, 3) + covariance(4, 3);
  const Scalar _tmp162 = -_tmp155 * covariance(2, 1) - _tmp156 * covariance(1, 1) -
                         _tmp157 * covariance(3, 1) - _tmp158 * covariance(0, 1) + covariance(4, 1);
  const Scalar _tmp163 = -_tmp155 * covariance(2, 2) - _tmp156 * covariance(1, 2) -
                         _tmp157 * covariance(3, 2) - _tmp158 * covariance(0, 2) + covariance(4, 2);
  const Scalar _tmp164 = _tmp95 * measurement_noise(2, 2) + _tmp96 * measurement_noise(1, 2) +
                         _tmp97 * measurement_noise(0, 2);
  const Scalar _tmp165 = _tmp95 * measurement_noise(2, 0) + _tmp96 * measurement_noise(1, 0) +
                         _tmp97 * measurement_noise(0, 0);
  const Scalar _tmp166 = _tmp101 * measurement_noise(1, 0) + _tmp102 * measurement_noise(2, 0) +
                         _tmp103 * measurement_noise(0, 0);
  const Scalar _tmp167 = _tmp101 * measurement_noise(1, 1) + _tmp102 * measurement_noise(2, 1) +
                         _tmp103 * measurement_noise(0, 1);
  const Scalar _tmp168 = 2 * _tmp103;
  const Scalar _tmp169 = _tmp101 * _tmp2 - _tmp168 * state(2, 0);
  const Scalar _tmp170 = -_tmp101 * _tmp5 - _tmp168 * state(1, 0);
  const Scalar _tmp171 = _tmp0 * _tmp101 + _tmp102 * _tmp19 - _tmp103 * _tmp3;
  const Scalar _tmp172 = -_tmp0 * _tmp103 - _tmp101 * _tmp3 + _tmp102 * _tmp20;
  const Scalar _tmp173 = -_tmp169 * covariance(0, 3) - _tmp170 * covariance(3, 3) -
                         _tmp171 * covariance(1, 3) - _tmp172 * covariance(2, 3) + covariance(5, 3);
  const Scalar _tmp174 = _tmp101 * measurement_noise(1, 2) + _tmp102 * measurement_noise(2, 2) +
                         _tmp103 * measurement_noise(0, 2);
  const Scalar _tmp175 = -_tmp169 * covariance(0, 0) - _tmp170 * covariance(3, 0) -
                         _tmp171 * covariance(1, 0) - _tmp172 * covariance(2, 0) + covariance(5, 0);
  const Scalar _tmp176 = -_tmp169 * covariance(0, 1) - _tmp170 * covariance(3, 1) -
                         _tmp171 * covariance(1, 1) - _tmp172 * covariance(2, 1) + covariance(5, 1);
  const Scalar _tmp177 = -_tmp169 * covariance(0, 2) - _tmp170 * covariance(3, 2) -
                         _tmp171 * covariance(1, 2) - _tmp172 * covariance(2, 2) + covariance(5, 2);
  const Scalar _tmp178 = _tmp107 * measurement_noise(0, 2) + _tmp108 * measurement_noise(1, 2) +
                         _tmp109 * measurement_noise(2, 2);
  const Scalar _tmp179 = _tmp0 * _tmp108 - _tmp107 * _tmp3 + _tmp109 * _tmp19;
  const Scalar _tmp180 = -_tmp0 * _tmp107 - _tmp108 * _tmp3 + _tmp109 * _tmp20;
  const Scalar _tmp181 = -_tmp107 * _tmp2 - _tmp108 * _tmp5;
  const Scalar _tmp182 = -_tmp107 * _tmp5 + _tmp108 * _tmp2;
  const Scalar _tmp183 = -_tmp179 * covariance(1, 1) - _tmp180 * covariance(2, 1) -
                         _tmp181 * covariance(3, 1) - _tmp182 * covariance(0, 1) + covariance(6, 1);
  const Scalar _tmp184 = -_tmp179 * covariance(1, 2) - _tmp180 * covariance(2, 2) -
                         _tmp181 * covariance(3, 2) - _tmp182 * covariance(0, 2) + covariance(6, 2);
  const Scalar _tmp185 = -_tmp179 * covariance(1, 3) - _tmp180 * covariance(2, 3) -
                         _tmp181 * covariance(3, 3) - _tmp182 * covariance(0, 3) + covariance(6, 3);
  const Scalar _tmp186 = _tmp107 * measurement_noise(0, 1) + _tmp108 * measurement_noise(1, 1) +
                         _tmp109 * measurement_noise(2, 1);
  const Scalar _tmp187 = _tmp107 * measurement_noise(0, 0) + _tmp108 * measurement_noise(1, 0) +
                         _tmp109 * measurement_noise(2, 0);
  const Scalar _tmp188 = -_tmp179 * covariance(1, 0) - _tmp180 * covariance(2, 0) -
                         _tmp181 * covariance(3, 0) - _tmp182 * covariance(0, 0) + covariance(6, 0);

  // Output terms (2)
  if (new_state != nullptr) {
    Eigen::Matrix<Scalar, 7, 1>& _new_state = (*new_state);

    _new_state(0, 0) = _tmp90 * _tmp91;
    _new_state(1, 0) = _tmp75 * _tmp91;
    _new_state(2, 0) = _tmp68 * _tmp91;
    _new_state(3, 0) = _tmp83 * _tmp91;
    _new_state(4, 0) = _tmp56 * _tmp97 + _tmp61 * _tmp95 + _tmp67 * _tmp96 + state(4, 0);
    _new_state(5, 0) = _tmp101 * _tmp67 + _tmp102 * _tmp61 + _tmp103 * _tmp56 + state(5, 0);
    _new_state(6, 0) = _tmp107 * _tmp56 + _tmp108 * _tmp67 + _tmp109 * _tmp61 + state(6, 0);
  }

  if (new_covariance != nullptr) {
    Eigen::Matrix<Scalar, 7, 7>& _new_covariance = (*new_covariance);

    _new_covariance(0, 0) = _tmp110 * _tmp88 + _tmp111 * _tmp89 - _tmp112 * _tmp116 -
                            _tmp113 * _tmp119 - _tmp114 * _tmp120 + _tmp115 * _tmp118 +
                            _tmp117 * _tmp87;
    _new_covariance(1, 0) = -_tmp112 * _tmp130 - _tmp113 * _tmp129 - _tmp114 * _tmp128 +
                            _tmp115 * _tmp127 + _tmp121 * _tmp88 + _tmp122 * _tmp89 +
                            _tmp131 * _tmp87;
    _new_covariance(2, 0) = -_tmp112 * _tmp137 - _tmp113 * _tmp142 - _tmp114 * _tmp140 +
                            _tmp115 * _tmp139 + _tmp138 * _tmp89 + _tmp141 * _tmp88 +
                            _tmp143 * _tmp87;
    _new_covariance(3, 0) = -_tmp112 * _tmp150 - _tmp113 * _tmp152 - _tmp114 * _tmp151 +
                            _tmp115 * _tmp154 + _tmp144 * _tmp87 + _tmp145 * _tmp88 +
                            _tmp153 * _tmp89;
    _new_covariance(4, 0) = -_tmp112 * _tmp161 - _tmp113 * _tmp162 - _tmp114 * _tmp163 +
                            _tmp115 * _tmp159 + _tmp160 * _tmp88 + _tmp164 * _tmp89 +
                            _tmp165 * _tmp87;
    _new_covariance(5, 0) = -_tmp112 * _tmp173 - _tmp113 * _tmp176 - _tmp114 * _tmp177 +
                            _tmp115 * _tmp175 + _tmp166 * _tmp87 + _tmp167 * _tmp88 +
                            _tmp174 * _tmp89;
    _new_covariance(6, 0) = -_tmp112 * _tmp185 - _tmp113 * _tmp183 - _tmp114 * _tmp184 +
                            _tmp115 * _tmp188 + _tmp178 * _tmp89 + _tmp186 * _tmp88 +
                            _tmp187 * _tmp87;
    _new_covariance(0, 1) = _tmp110 * _tmp72 + _tmp111 * _tmp74 - _tmp116 * _tmp125 +
                            _tmp117 * _tmp73 - _tmp118 * _tmp126 + _tmp119 * _tmp124 -
                            _tmp120 * _tmp123;
    _new_covariance(1, 1) = _tmp121 * _tmp72 + _tmp122 * _tmp74 - _tmp123 * _tmp128 +
                            _tmp124 * _tmp129 - _tmp125 * _tmp130 - _tmp126 * _tmp127 +
                            _tmp131 * _tmp73;
    _new_covariance(2, 1) = -_tmp123 * _tmp140 + _tmp124 * _tmp142 - _tmp125 * _tmp137 -
                            _tmp126 * _tmp139 + _tmp138 * _tmp74 + _tmp141 * _tmp72 +
                            _tmp143 * _tmp73;
    _new_covariance(3, 1) = -_tmp123 * _tmp151 + _tmp124 * _tmp152 - _tmp125 * _tmp150 -
                            _tmp126 * _tmp154 + _tmp144 * _tmp73 + _tmp145 * _tmp72 +
                            _tmp153 * _tmp74;
    _new_covariance(4, 1) = -_tmp123 * _tmp163 + _tmp124 * _tmp162 - _tmp125 * _tmp161 -
                            _tmp126 * _tmp159 + _tmp160 * _tmp72 + _tmp164 * _tmp74 +
                            _tmp165 * _tmp73;
    _new_covariance(5, 1) = -_tmp123 * _tmp177 + _tmp124 * _tmp176 - _tmp125 * _tmp173 -
                            _tmp126 * _tmp175 + _tmp166 * _tmp73 + _tmp167 * _tmp72 +
                            _tmp174 * _tmp74;
    _new_covariance(6, 1) = -_tmp123 * _tmp184 + _tmp124 * _tmp183 - _tmp125 * _tmp185 -
                            _tmp126 * _tmp188 + _tmp178 * _tmp74 + _tmp186 * _tmp72 +
                            _tmp187 * _tmp73;
    _new_covariance(0, 2) = _tmp110 * _tmp66 + _tmp111 * _tmp60 - _tmp116 * _tmp133 +
                            _tmp117 * _tmp55 - _tmp118 * _tmp134 - _tmp119 * _tmp136 +
                            _tmp120 * _tmp135;
    _new_covariance(1, 2) = _tmp121 * _tmp66 + _tmp122 * _tmp60 - _tmp127 * _tmp134 +
                            _tmp128 * _tmp135 - _tmp129 * _tmp136 - _tmp130 * _tmp133 +
                            _tmp131 * _tmp55;
    _new_covariance(2, 2) = -_tmp133 * _tmp137 - _tmp134 * _tmp139 + _tmp135 * _tmp140 -
                            _tmp136 * _tmp142 + _tmp138 * _tmp60 + _tmp141 * _tmp66 +
                            _tmp143 * _tmp55;
    _new_covariance(3, 2) = -_tmp133 * _tmp150 - _tmp134 * _tmp154 + _tmp135 * _tmp151 -
                            _tmp136 * _tmp152 + _tmp144 * _tmp55 + _tmp145 * _tmp66 +
                            _tmp153 * _tmp60;
    _new_covariance(4, 2) = -_tmp133 * _tmp161 - _tmp134 * _tmp159 + _tmp135 * _tmp163 -
                            _tmp136 * _tmp162 + _tmp160 * _tmp66 + _tmp164 * _tmp60 +
                            _tmp165 * _tmp55;
    _new_covariance(5, 2) = -_tmp133 * _tmp173 - _tmp134 * _tmp175 + _tmp135 * _tmp177 -
                            _tmp136 * _tmp176 + _tmp166 * _tmp55 + _tmp167 * _tmp66 +
                            _tmp174 * _tmp60;
    _new_covariance(6, 2) = -_tmp133 * _tmp185 - _tmp134 * _tmp188 + _tmp135 * _tmp184 -
                            _tmp136 * _tmp183 + _tmp178 * _tmp60 + _tmp186 * _tmp66 +
                            _tmp187 * _tmp55;
    _new_covariance(0, 3) = _tmp110 * _tmp80 + _tmp111 * _tmp81 + _tmp116 * _tmp146 +
                            _tmp117 * _tmp82 - _tmp118 * _tmp147 - _tmp119 * _tmp149 -
                            _tmp120 * _tmp148;
    _new_covariance(1, 3) = _tmp121 * _tmp80 + _tmp122 * _tmp81 - _tmp127 * _tmp147 -
                            _tmp128 * _tmp148 - _tmp129 * _tmp149 + _tmp130 * _tmp146 +
                            _tmp131 * _tmp82;
    _new_covariance(2, 3) = _tmp137 * _tmp146 + _tmp138 * _tmp81 - _tmp139 * _tmp147 -
                            _tmp140 * _tmp148 + _tmp141 * _tmp80 - _tmp142 * _tmp149 +
                            _tmp143 * _tmp82;
    _new_covariance(3, 3) = _tmp144 * _tmp82 + _tmp145 * _tmp80 + _tmp146 * _tmp150 -
                            _tmp147 * _tmp154 - _tmp148 * _tmp151 - _tmp149 * _tmp152 +
                            _tmp153 * _tmp81;
    _new_covariance(4, 3) = _tmp146 * _tmp161 - _tmp147 * _tmp159 - _tmp148 * _tmp163 -
                            _tmp149 * _tmp162 + _tmp160 * _tmp80 + _tmp164 * _tmp81 +
                            _tmp165 * _tmp82;
    _new_covariance(5, 3) = _tmp146 * _tmp173 - _tmp147 * _tmp175 - _tmp148 * _tmp177 -
                            _tmp149 * _tmp176 + _tmp166 * _tmp82 + _tmp167 * _tmp80 +
                            _tmp174 * _tmp81;
    _new_covariance(6, 3) = _tmp146 * _tmp185 - _tmp147 * _tmp188 - _tmp148 * _tmp184 -
                            _tmp149 * _tmp183 + _tmp178 * _tmp81 + _tmp186 * _tmp80 +
                            _tmp187 * _tmp82;
    _new_covariance(0, 4) = _tmp110 * _tmp96 + _tmp111 * _tmp95 - _tmp112 * covariance(3, 4) -
                            _tmp113 * covariance(1, 4) - _tmp114 * covariance(2, 4) +
                            _tmp115 * covariance(0, 4) - _tmp116 * _tmp157 + _tmp117 * _tmp97 -
                            _tmp118 * _tmp158 - _tmp119 * _tmp156 - _tmp120 * _tmp155;
    _new_covariance(1, 4) = _tmp121 * _tmp96 + _tmp122 * _tmp95 - _tmp123 * covariance(2, 4) +
                            _tmp124 * covariance(1, 4) - _tmp125 * covariance(3, 4) -
                            _tmp126 * covariance(0, 4) - _tmp127 * _tmp158 - _tmp128 * _tmp155 -
                            _tmp129 * _tmp156 - _tmp130 * _tmp157 + _tmp131 * _tmp97;
    _new_covariance(2, 4) =
        -_tmp133 * covariance(3, 4) - _tmp134 * covariance(0, 4) + _tmp135 * covariance(2, 4) -
        _tmp136 * covariance(1, 4) - _tmp137 * _tmp157 + _tmp138 * _tmp95 - _tmp139 * _tmp158 -
        _tmp140 * _tmp155 + _tmp141 * _tmp96 - _tmp142 * _tmp156 + _tmp143 * _tmp97;
    _new_covariance(3, 4) = _tmp144 * _tmp97 + _tmp145 * _tmp96 + _tmp146 * covariance(3, 4) -
                            _tmp147 * covariance(0, 4) - _tmp148 * covariance(2, 4) -
                            _tmp149 * covariance(1, 4) - _tmp150 * _tmp157 - _tmp151 * _tmp155 -
                            _tmp152 * _tmp156 + _tmp153 * _tmp95 - _tmp154 * _tmp158;
    _new_covariance(4, 4) = -_tmp155 * _tmp163 - _tmp155 * covariance(2, 4) - _tmp156 * _tmp162 -
                            _tmp156 * covariance(1, 4) - _tmp157 * _tmp161 -
                            _tmp157 * covariance(3, 4) - _tmp158 * _tmp159 -
                            _tmp158 * covariance(0, 4) + _tmp160 * _tmp96 + _tmp164 * _tmp95 +
                            _tmp165 * _tmp97 + covariance(4, 4);
    _new_covariance(5, 4) = -_tmp155 * _tmp177 - _tmp156 * _tmp176 - _tmp157 * _tmp173 -
                            _tmp158 * _tmp175 + _tmp166 * _tmp97 + _tmp167 * _tmp96 -
                            _tmp169 * covariance(0, 4) - _tmp170 * covariance(3, 4) -
                            _tmp171 * covariance(1, 4) - _tmp172 * covariance(2, 4) +
                            _tmp174 * _tmp95 + covariance(5, 4);
    _new_covariance(6, 4) = -_tmp155 * _tmp184 - _tmp156 * _tmp183 - _tmp157 * _tmp185 -
                            _tmp158 * _tmp188 + _tmp178 * _tmp95 - _tmp179 * covariance(1, 4) -
                            _tmp180 * covariance(2, 4) - _tmp181 * covariance(3, 4) -
                            _tmp182 * covariance(0, 4) + _tmp186 * _tmp96 + _tmp187 * _tmp97 +
                            covariance(6, 4);
    _new_covariance(0, 5) =
        _tmp101 * _tmp110 + _tmp102 * _tmp111 + _tmp103 * _tmp117 - _tmp112 * covariance(3, 5) -
        _tmp113 * covariance(1, 5) - _tmp114 * covariance(2, 5) + _tmp115 * covariance(0, 5) -
        _tmp116 * _tmp170 - _tmp118 * _tmp169 - _tmp119 * _tmp171 - _tmp120 * _tmp172;
    _new_covariance(1, 5) =
        _tmp101 * _tmp121 + _tmp102 * _tmp122 + _tmp103 * _tmp131 - _tmp123 * covariance(2, 5) +
        _tmp124 * covariance(1, 5) - _tmp125 * covariance(3, 5) - _tmp126 * covariance(0, 5) -
        _tmp127 * _tmp169 - _tmp128 * _tmp172 - _tmp129 * _tmp171 - _tmp130 * _tmp170;
    _new_covariance(2, 5) =
        _tmp101 * _tmp141 + _tmp102 * _tmp138 + _tmp103 * _tmp143 - _tmp133 * covariance(3, 5) -
        _tmp134 * covariance(0, 5) + _tmp135 * covariance(2, 5) - _tmp136 * covariance(1, 5) -
        _tmp137 * _tmp170 - _tmp139 * _tmp169 - _tmp140 * _tmp172 - _tmp142 * _tmp171;
    _new_covariance(3, 5) =
        _tmp101 * _tmp145 + _tmp102 * _tmp153 + _tmp103 * _tmp144 + _tmp146 * covariance(3, 5) -
        _tmp147 * covariance(0, 5) - _tmp148 * covariance(2, 5) - _tmp149 * covariance(1, 5) -
        _tmp150 * _tmp170 - _tmp151 * _tmp172 - _tmp152 * _tmp171 - _tmp154 * _tmp169;
    _new_covariance(4, 5) = _tmp101 * _tmp160 + _tmp102 * _tmp164 + _tmp103 * _tmp165 -
                            _tmp155 * covariance(2, 5) - _tmp156 * covariance(1, 5) -
                            _tmp157 * covariance(3, 5) - _tmp158 * covariance(0, 5) -
                            _tmp159 * _tmp169 - _tmp161 * _tmp170 - _tmp162 * _tmp171 -
                            _tmp163 * _tmp172 + covariance(4, 5);
    _new_covariance(5, 5) = _tmp101 * _tmp167 + _tmp102 * _tmp174 + _tmp103 * _tmp166 -
                            _tmp169 * _tmp175 - _tmp169 * covariance(0, 5) - _tmp170 * _tmp173 -
                            _tmp170 * covariance(3, 5) - _tmp171 * _tmp176 -
                            _tmp171 * covariance(1, 5) - _tmp172 * _tmp177 -
                            _tmp172 * covariance(2, 5) + covariance(5, 5);
    _new_covariance(6, 5) = _tmp101 * _tmp186 + _tmp102 * _tmp178 + _tmp103 * _tmp187 -
                            _tmp169 * _tmp188 - _tmp170 * _tmp185 - _tmp171 * _tmp183 -
                            _tmp172 * _tmp184 - _tmp179 * covariance(1, 5) -
                            _tmp180 * covariance(2, 5) - _tmp181 * covariance(3, 5) -
                            _tmp182 * covariance(0, 5) + covariance(6, 5);
    _new_covariance(0, 6) =
        _tmp107 * _tmp117 + _tmp108 * _tmp110 + _tmp109 * _tmp111 - _tmp112 * covariance(3, 6) -
        _tmp113 * covariance(1, 6) - _tmp114 * covariance(2, 6) + _tmp115 * covariance(0, 6) -
        _tmp116 * _tmp181 - _tmp118 * _tmp182 - _tmp119 * _tmp179 - _tmp120 * _tmp180;
    _new_covariance(1, 6) =
        _tmp107 * _tmp131 + _tmp108 * _tmp121 + _tmp109 * _tmp122 - _tmp123 * covariance(2, 6) +
        _tmp124 * covariance(1, 6) - _tmp125 * covariance(3, 6) - _tmp126 * covariance(0, 6) -
        _tmp127 * _tmp182 - _tmp128 * _tmp180 - _tmp129 * _tmp179 - _tmp130 * _tmp181;
    _new_covariance(2, 6) =
        _tmp107 * _tmp143 + _tmp108 * _tmp141 + _tmp109 * _tmp138 - _tmp133 * covariance(3, 6) -
        _tmp134 * covariance(0, 6) + _tmp135 * covariance(2, 6) - _tmp136 * covariance(1, 6) -
        _tmp137 * _tmp181 - _tmp139 * _tmp182 - _tmp140 * _tmp180 - _tmp142 * _tmp179;
    _new_covariance(3, 6) =
        _tmp107 * _tmp144 + _tmp108 * _tmp145 + _tmp109 * _tmp153 + _tmp146 * covariance(3, 6) -
        _tmp147 * covariance(0, 6) - _tmp148 * covariance(2, 6) - _tmp149 * covariance(1, 6) -
        _tmp150 * _tmp181 - _tmp151 * _tmp180 - _tmp152 * _tmp179 - _tmp154 * _tmp182;
    _new_covariance(4, 6) = _tmp107 * _tmp165 + _tmp108 * _tmp160 + _tmp109 * _tmp164 -
                            _tmp155 * covariance(2, 6) - _tmp156 * covariance(1, 6) -
                            _tmp157 * covariance(3, 6) - _tmp158 * covariance(0, 6) -
                            _tmp159 * _tmp182 - _tmp161 * _tmp181 - _tmp162 * _tmp179 -
                            _tmp163 * _tmp180 + covariance(4, 6);
    _new_covariance(5, 6) = _tmp107 * _tmp166 + _tmp108 * _tmp167 + _tmp109 * _tmp174 -
                            _tmp169 * covariance(0, 6) - _tmp170 * covariance(3, 6) -
                            _tmp171 * covariance(1, 6) - _tmp172 * covariance(2, 6) -
                            _tmp173 * _tmp181 - _tmp175 * _tmp182 - _tmp176 * _tmp179 -
                            _tmp177 * _tmp180 + covariance(5, 6);
    _new_covariance(6, 6) = _tmp107 * _tmp187 + _tmp108 * _tmp186 + _tmp109 * _tmp178 -
                            _tmp179 * _tmp183 - _tmp179 * covariance(1, 6) - _tmp180 * _tmp184 -
                            _tmp180 * covariance(2, 6) - _tmp181 * _tmp185 -
                            _tmp181 * covariance(3, 6) - _tmp182 * _tmp188 -
                            _tmp182 * covariance(0, 6) + covariance(6, 6);
  }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
