// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by hand.
 *
 * Symbolic function: update_sym
 *
 * Args:
 *     state: Matrix71
 *     covariance: Matrix77
 *     measurement: Matrix31
 *     measurement_noise: Matrix33
 *
 * Outputs:
 *     new_state: Matrix71
 *     new_covariance: Matrix77
 */
template <typename Scalar>
void Update(const Eigen::Matrix<Scalar, 7, 1>& state, const Eigen::Matrix<Scalar, 7, 7>& covariance,
            const Eigen::Matrix<Scalar, 3, 1>& measurement,
            const Eigen::Matrix<Scalar, 3, 3>& measurement_noise,
            Eigen::Matrix<Scalar, 7, 1>* const new_state = nullptr,
            Eigen::Matrix<Scalar, 7, 7>* const new_covariance = nullptr) {
  // Total ops: 1713

  // Input arrays

  // Intermediate terms (187)
  const Scalar _tmp0 = Scalar(-19.620000000000001);
  const Scalar _tmp1 = _tmp0 * state(0, 0);
  const Scalar _tmp2 = 2 * state(1, 0);
  const Scalar _tmp3 = -Scalar(9.8100000000000005) * _tmp2;
  const Scalar _tmp4 = _tmp3 * covariance(3, 0);
  const Scalar _tmp5 = 2 * state(2, 0);
  const Scalar _tmp6 = -Scalar(9.8100000000000005) * _tmp5;
  const Scalar _tmp7 = _tmp6 * covariance(3, 3);
  const Scalar _tmp8 = _tmp0 * state(3, 0);
  const Scalar _tmp9 = _tmp1 * covariance(3, 1) + _tmp4 + _tmp7 + _tmp8 * covariance(3, 2);
  const Scalar _tmp10 = _tmp6 * covariance(0, 3);
  const Scalar _tmp11 = _tmp3 * covariance(3, 3);
  const Scalar _tmp12 = -_tmp1 * covariance(2, 3) - _tmp10 + _tmp11 + _tmp8 * covariance(1, 3);
  const Scalar _tmp13 = _tmp1 * covariance(2, 1);
  const Scalar _tmp14 = _tmp8 * covariance(1, 1);
  const Scalar _tmp15 = -_tmp13 + _tmp14 + _tmp3 * covariance(3, 1) - _tmp6 * covariance(0, 1);
  const Scalar _tmp16 = -_tmp1 * covariance(2, 2);
  const Scalar _tmp17 = _tmp8 * covariance(1, 2);
  const Scalar _tmp18 = _tmp16 + _tmp17 + _tmp3 * covariance(3, 2) - _tmp6 * covariance(0, 2);
  const Scalar _tmp19 = -_tmp6 * covariance(0, 0);
  const Scalar _tmp20 = -_tmp1 * covariance(2, 0) + _tmp19 + _tmp4 + _tmp8 * covariance(1, 0);
  const Scalar _tmp21 =
      _tmp1 * _tmp15 + _tmp12 * _tmp6 + _tmp18 * _tmp8 + _tmp20 * _tmp3 + measurement_noise(0, 1);
  const Scalar _tmp22 = _tmp3 * covariance(0, 3);
  const Scalar _tmp23 = _tmp1 * covariance(1, 3) + _tmp22 + _tmp7 + _tmp8 * covariance(2, 3);
  const Scalar _tmp24 = _tmp8 * covariance(2, 1);
  const Scalar _tmp25 = _tmp1 * covariance(1, 1);
  const Scalar _tmp26 = _tmp24 + _tmp25 + _tmp3 * covariance(0, 1) + _tmp6 * covariance(3, 1);
  const Scalar _tmp27 = _tmp8 * covariance(2, 2);
  const Scalar _tmp28 = _tmp1 * covariance(1, 2);
  const Scalar _tmp29 = _tmp27 + _tmp28 + _tmp3 * covariance(0, 2) + _tmp6 * covariance(3, 2);
  const Scalar _tmp30 = _tmp3 * covariance(0, 0);
  const Scalar _tmp31 = _tmp6 * covariance(3, 0);
  const Scalar _tmp32 = _tmp1 * covariance(1, 0) + _tmp30 + _tmp31 + _tmp8 * covariance(2, 0);
  const Scalar _tmp33 = Scalar(1.0) / (-_tmp1 * _tmp18 + _tmp12 * _tmp3 + _tmp15 * _tmp8 -
                                       _tmp20 * _tmp6 + measurement_noise(0, 0));
  const Scalar _tmp34 = _tmp33 * (-_tmp1 * _tmp29 + _tmp23 * _tmp3 + _tmp26 * _tmp8 -
                                  _tmp32 * _tmp6 + measurement_noise(1, 0));
  const Scalar _tmp35 = Scalar(1.0) / (_tmp1 * _tmp26 - _tmp21 * _tmp34 + _tmp23 * _tmp6 +
                                       _tmp29 * _tmp8 + _tmp3 * _tmp32 + measurement_noise(1, 1));
  const Scalar _tmp36 = Scalar(-39.240000000000002);
  const Scalar _tmp37 = _tmp36 * state(1, 0);
  const Scalar _tmp38 = _tmp36 * state(2, 0);
  const Scalar _tmp39 = -_tmp15 * _tmp37 - _tmp18 * _tmp38 + measurement_noise(0, 2);
  const Scalar _tmp40 =
      -_tmp26 * _tmp37 - _tmp29 * _tmp38 - _tmp34 * _tmp39 + measurement_noise(1, 2);
  const Scalar _tmp41 = -_tmp37 * covariance(1, 3) - _tmp38 * covariance(2, 3);
  const Scalar _tmp42 = -_tmp38 * covariance(2, 2);
  const Scalar _tmp43 = -_tmp37 * covariance(1, 2) + _tmp42;
  const Scalar _tmp44 = -_tmp37 * covariance(1, 0) - _tmp38 * covariance(2, 0);
  const Scalar _tmp45 = -_tmp37 * covariance(1, 1);
  const Scalar _tmp46 = -_tmp38 * covariance(2, 1) + _tmp45;
  const Scalar _tmp47 = _tmp33 * (-_tmp1 * _tmp43 + _tmp3 * _tmp41 - _tmp44 * _tmp6 +
                                  _tmp46 * _tmp8 + measurement_noise(2, 0));
  const Scalar _tmp48 = _tmp35 * (_tmp1 * _tmp46 - _tmp21 * _tmp47 + _tmp3 * _tmp44 +
                                  _tmp41 * _tmp6 + _tmp43 * _tmp8 + measurement_noise(2, 1));
  const Scalar _tmp49 = Scalar(1.0) / (-_tmp37 * _tmp46 - _tmp38 * _tmp43 - _tmp39 * _tmp47 -
                                       _tmp40 * _tmp48 + measurement_noise(2, 2));
  const Scalar _tmp50 = _tmp40 * _tmp49;
  const Scalar _tmp51 = _tmp35 * _tmp50;
  const Scalar _tmp52 = -_tmp1 * covariance(3, 2) + _tmp11 - _tmp31 + _tmp8 * covariance(3, 1);
  const Scalar _tmp53 = _tmp39 * _tmp49;
  const Scalar _tmp54 = _tmp33 * (_tmp21 * _tmp51 - _tmp53);
  const Scalar _tmp55 = _tmp49 * (-_tmp37 * covariance(3, 1) - _tmp38 * covariance(3, 2));
  const Scalar _tmp56 = -_tmp51 * _tmp9 + _tmp52 * _tmp54 + _tmp55;
  const Scalar _tmp57 =
      measurement(2, 0) - Scalar(19.620000000000001) * std::pow(state(1, 0), Scalar(2)) -
      Scalar(19.620000000000001) * std::pow(state(2, 0), Scalar(2)) + Scalar(9.8100000000000005);
  const Scalar _tmp58 = Scalar(9.8100000000000005) * _tmp2 * state(3, 0) -
                        Scalar(9.8100000000000005) * _tmp5 * state(0, 0) + measurement(0, 0);
  const Scalar _tmp59 = _tmp34 * _tmp48 - _tmp47;
  const Scalar _tmp60 = _tmp35 * (-_tmp34 - _tmp50 * _tmp59);
  const Scalar _tmp61 = _tmp33 * (-_tmp21 * _tmp60 - _tmp53 * _tmp59 + 1);
  const Scalar _tmp62 = _tmp52 * _tmp61 + _tmp55 * _tmp59 + _tmp60 * _tmp9;
  const Scalar _tmp63 = _tmp35 * (_tmp48 * _tmp50 + 1);
  const Scalar _tmp64 = _tmp33 * (-_tmp21 * _tmp63 + _tmp48 * _tmp53);
  const Scalar _tmp65 = -_tmp48 * _tmp55 + _tmp52 * _tmp64 + _tmp63 * _tmp9;
  const Scalar _tmp66 = Scalar(9.8100000000000005) * _tmp2 * state(0, 0) +
                        Scalar(9.8100000000000005) * _tmp5 * state(3, 0) + measurement(1, 0);
  const Scalar _tmp67 = _tmp56 * _tmp57 + _tmp58 * _tmp62 + _tmp65 * _tmp66 + state(3, 0);
  const Scalar _tmp68 = _tmp49 * (-_tmp37 * covariance(2, 1) + _tmp42);
  const Scalar _tmp69 = _tmp16 + _tmp24 + _tmp3 * covariance(2, 3) - _tmp6 * covariance(2, 0);
  const Scalar _tmp70 = _tmp13 + _tmp27 + _tmp3 * covariance(2, 0) + _tmp6 * covariance(2, 3);
  const Scalar _tmp71 = -_tmp48 * _tmp68 + _tmp63 * _tmp70 + _tmp64 * _tmp69;
  const Scalar _tmp72 = -_tmp51 * _tmp70 + _tmp54 * _tmp69 + _tmp68;
  const Scalar _tmp73 = _tmp59 * _tmp68 + _tmp60 * _tmp70 + _tmp61 * _tmp69;
  const Scalar _tmp74 = _tmp57 * _tmp72 + _tmp58 * _tmp73 + _tmp66 * _tmp71 + state(2, 0);
  const Scalar _tmp75 = -_tmp1 * covariance(0, 2) + _tmp19 + _tmp22 + _tmp8 * covariance(0, 1);
  const Scalar _tmp76 = _tmp49 * (-_tmp37 * covariance(0, 1) - _tmp38 * covariance(0, 2));
  const Scalar _tmp77 = _tmp1 * covariance(0, 1) + _tmp10 + _tmp30 + _tmp8 * covariance(0, 2);
  const Scalar _tmp78 = -_tmp48 * _tmp76 + _tmp63 * _tmp77 + _tmp64 * _tmp75;
  const Scalar _tmp79 = _tmp59 * _tmp76 + _tmp60 * _tmp77 + _tmp61 * _tmp75;
  const Scalar _tmp80 = -_tmp51 * _tmp77 + _tmp54 * _tmp75 + _tmp76;
  const Scalar _tmp81 = _tmp57 * _tmp80 + _tmp58 * _tmp79 + _tmp66 * _tmp78 + state(0, 0);
  const Scalar _tmp82 = _tmp17 + _tmp25 + _tmp3 * covariance(1, 0) + _tmp6 * covariance(1, 3);
  const Scalar _tmp83 = _tmp49 * (-_tmp38 * covariance(1, 2) + _tmp45);
  const Scalar _tmp84 = _tmp14 - _tmp28 + _tmp3 * covariance(1, 3) - _tmp6 * covariance(1, 0);
  const Scalar _tmp85 = -_tmp48 * _tmp83 + _tmp63 * _tmp82 + _tmp64 * _tmp84;
  const Scalar _tmp86 = _tmp59 * _tmp83 + _tmp60 * _tmp82 + _tmp61 * _tmp84;
  const Scalar _tmp87 = -_tmp51 * _tmp82 + _tmp54 * _tmp84 + _tmp83;
  const Scalar _tmp88 = _tmp57 * _tmp87 + _tmp58 * _tmp86 + _tmp66 * _tmp85 + state(1, 0);
  const Scalar _tmp89 = std::pow(Scalar(std::pow(_tmp67, Scalar(2)) + std::pow(_tmp74, Scalar(2)) +
                                        std::pow(_tmp81, Scalar(2)) + std::pow(_tmp88, Scalar(2))),
                                 Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp90 = _tmp1 * covariance(4, 1) + _tmp3 * covariance(4, 0) +
                        _tmp6 * covariance(4, 3) + _tmp8 * covariance(4, 2);
  const Scalar _tmp91 = -_tmp1 * covariance(4, 2) + _tmp3 * covariance(4, 3) -
                        _tmp6 * covariance(4, 0) + _tmp8 * covariance(4, 1);
  const Scalar _tmp92 = _tmp49 * (-_tmp37 * covariance(4, 1) - _tmp38 * covariance(4, 2));
  const Scalar _tmp93 = _tmp59 * _tmp92 + _tmp60 * _tmp90 + _tmp61 * _tmp91;
  const Scalar _tmp94 = -_tmp48 * _tmp92 + _tmp63 * _tmp90 + _tmp64 * _tmp91;
  const Scalar _tmp95 = -_tmp51 * _tmp90 + _tmp54 * _tmp91 + _tmp92;
  const Scalar _tmp96 = _tmp1 * covariance(5, 1) + _tmp3 * covariance(5, 0) +
                        _tmp6 * covariance(5, 3) + _tmp8 * covariance(5, 2);
  const Scalar _tmp97 = _tmp49 * (-_tmp37 * covariance(5, 1) - _tmp38 * covariance(5, 2));
  const Scalar _tmp98 = -_tmp1 * covariance(5, 2) + _tmp3 * covariance(5, 3) -
                        _tmp6 * covariance(5, 0) + _tmp8 * covariance(5, 1);
  const Scalar _tmp99 = -_tmp51 * _tmp96 + _tmp54 * _tmp98 + _tmp97;
  const Scalar _tmp100 = _tmp59 * _tmp97 + _tmp60 * _tmp96 + _tmp61 * _tmp98;
  const Scalar _tmp101 = -_tmp48 * _tmp97 + _tmp63 * _tmp96 + _tmp64 * _tmp98;
  const Scalar _tmp102 = _tmp49 * (-_tmp37 * covariance(6, 1) - _tmp38 * covariance(6, 2));
  const Scalar _tmp103 = -_tmp1 * covariance(6, 2) + _tmp3 * covariance(6, 3) -
                         _tmp6 * covariance(6, 0) + _tmp8 * covariance(6, 1);
  const Scalar _tmp104 = _tmp1 * covariance(6, 1) + _tmp3 * covariance(6, 0) +
                         _tmp6 * covariance(6, 3) + _tmp8 * covariance(6, 2);
  const Scalar _tmp105 = _tmp102 * _tmp59 + _tmp103 * _tmp61 + _tmp104 * _tmp60;
  const Scalar _tmp106 = -_tmp102 * _tmp48 + _tmp103 * _tmp64 + _tmp104 * _tmp63;
  const Scalar _tmp107 = _tmp102 + _tmp103 * _tmp54 - _tmp104 * _tmp51;
  const Scalar _tmp108 = _tmp78 * measurement_noise(1, 0) + _tmp79 * measurement_noise(0, 0) +
                         _tmp80 * measurement_noise(2, 0);
  const Scalar _tmp109 = _tmp78 * measurement_noise(1, 2) + _tmp79 * measurement_noise(0, 2) +
                         _tmp80 * measurement_noise(2, 2);
  const Scalar _tmp110 = _tmp78 * measurement_noise(1, 1) + _tmp79 * measurement_noise(0, 1) +
                         _tmp80 * measurement_noise(2, 1);
  const Scalar _tmp111 = _tmp3 * _tmp79 + _tmp6 * _tmp78;
  const Scalar _tmp112 = -_tmp3 * _tmp78 + _tmp6 * _tmp79 + 1;
  const Scalar _tmp113 = _tmp1 * _tmp78 - _tmp37 * _tmp80 + _tmp79 * _tmp8;
  const Scalar _tmp114 = -_tmp1 * _tmp79 - _tmp38 * _tmp80 + _tmp78 * _tmp8;
  const Scalar _tmp115 = -_tmp111 * covariance(3, 3) + _tmp112 * covariance(0, 3) -
                         _tmp113 * covariance(1, 3) - _tmp114 * covariance(2, 3);
  const Scalar _tmp116 = -_tmp111 * covariance(3, 1) + _tmp112 * covariance(0, 1) -
                         _tmp113 * covariance(1, 1) - _tmp114 * covariance(2, 1);
  const Scalar _tmp117 = -_tmp111 * covariance(3, 2) + _tmp112 * covariance(0, 2) -
                         _tmp113 * covariance(1, 2) - _tmp114 * covariance(2, 2);
  const Scalar _tmp118 = -_tmp111 * covariance(3, 0) + _tmp112 * covariance(0, 0) -
                         _tmp113 * covariance(1, 0) - _tmp114 * covariance(2, 0);
  const Scalar _tmp119 = -_tmp1 * _tmp86 - _tmp38 * _tmp87 + _tmp8 * _tmp85;
  const Scalar _tmp120 = -_tmp1 * _tmp85 + _tmp37 * _tmp87 - _tmp8 * _tmp86 + 1;
  const Scalar _tmp121 = _tmp3 * _tmp85 - _tmp6 * _tmp86;
  const Scalar _tmp122 = _tmp3 * _tmp86 + _tmp6 * _tmp85;
  const Scalar _tmp123 = -_tmp119 * covariance(2, 0) + _tmp120 * covariance(1, 0) -
                         _tmp121 * covariance(0, 0) - _tmp122 * covariance(3, 0);
  const Scalar _tmp124 = -_tmp119 * covariance(2, 1) + _tmp120 * covariance(1, 1) -
                         _tmp121 * covariance(0, 1) - _tmp122 * covariance(3, 1);
  const Scalar _tmp125 = -_tmp119 * covariance(2, 2) + _tmp120 * covariance(1, 2) -
                         _tmp121 * covariance(0, 2) - _tmp122 * covariance(3, 2);
  const Scalar _tmp126 = _tmp85 * measurement_noise(1, 1) + _tmp86 * measurement_noise(0, 1) +
                         _tmp87 * measurement_noise(2, 1);
  const Scalar _tmp127 = _tmp85 * measurement_noise(1, 2) + _tmp86 * measurement_noise(0, 2) +
                         _tmp87 * measurement_noise(2, 2);
  const Scalar _tmp128 = _tmp85 * measurement_noise(1, 0) + _tmp86 * measurement_noise(0, 0) +
                         _tmp87 * measurement_noise(2, 0);
  const Scalar _tmp129 = -_tmp119 * covariance(2, 3) + _tmp120 * covariance(1, 3) -
                         _tmp121 * covariance(0, 3) - _tmp122 * covariance(3, 3);
  const Scalar _tmp130 = _tmp71 * measurement_noise(1, 2) + _tmp72 * measurement_noise(2, 2) +
                         _tmp73 * measurement_noise(0, 2);
  const Scalar _tmp131 = _tmp1 * _tmp71 - _tmp37 * _tmp72 + _tmp73 * _tmp8;
  const Scalar _tmp132 = _tmp1 * _tmp73 + _tmp38 * _tmp72 - _tmp71 * _tmp8 + 1;
  const Scalar _tmp133 = _tmp3 * _tmp71 - _tmp6 * _tmp73;
  const Scalar _tmp134 = _tmp3 * _tmp73 + _tmp6 * _tmp71;
  const Scalar _tmp135 = -_tmp131 * covariance(1, 3) + _tmp132 * covariance(2, 3) -
                         _tmp133 * covariance(0, 3) - _tmp134 * covariance(3, 3);
  const Scalar _tmp136 = _tmp71 * measurement_noise(1, 0) + _tmp72 * measurement_noise(2, 0) +
                         _tmp73 * measurement_noise(0, 0);
  const Scalar _tmp137 = -_tmp131 * covariance(1, 1) + _tmp132 * covariance(2, 1) -
                         _tmp133 * covariance(0, 1) - _tmp134 * covariance(3, 1);
  const Scalar _tmp138 = -_tmp131 * covariance(1, 2) + _tmp132 * covariance(2, 2) -
                         _tmp133 * covariance(0, 2) - _tmp134 * covariance(3, 2);
  const Scalar _tmp139 = _tmp71 * measurement_noise(1, 1) + _tmp72 * measurement_noise(2, 1) +
                         _tmp73 * measurement_noise(0, 1);
  const Scalar _tmp140 = -_tmp131 * covariance(1, 0) + _tmp132 * covariance(2, 0) -
                         _tmp133 * covariance(0, 0) - _tmp134 * covariance(3, 0);
  const Scalar _tmp141 = -_tmp3 * _tmp62 - _tmp6 * _tmp65 + 1;
  const Scalar _tmp142 = _tmp3 * _tmp65 - _tmp6 * _tmp62;
  const Scalar _tmp143 = _tmp0 * _tmp65;
  const Scalar _tmp144 = _tmp143 * state(0, 0) - _tmp37 * _tmp56 + _tmp62 * _tmp8;
  const Scalar _tmp145 = -_tmp1 * _tmp62 + _tmp143 * state(3, 0) - _tmp38 * _tmp56;
  const Scalar _tmp146 = _tmp141 * covariance(3, 0) - _tmp142 * covariance(0, 0) -
                         _tmp144 * covariance(1, 0) - _tmp145 * covariance(2, 0);
  const Scalar _tmp147 = _tmp56 * measurement_noise(2, 1) + _tmp62 * measurement_noise(0, 1) +
                         _tmp65 * measurement_noise(1, 1);
  const Scalar _tmp148 = _tmp141 * covariance(3, 1) - _tmp142 * covariance(0, 1) -
                         _tmp144 * covariance(1, 1) - _tmp145 * covariance(2, 1);
  const Scalar _tmp149 = _tmp141 * covariance(3, 2) - _tmp142 * covariance(0, 2) -
                         _tmp144 * covariance(1, 2) - _tmp145 * covariance(2, 2);
  const Scalar _tmp150 = _tmp141 * covariance(3, 3) - _tmp142 * covariance(0, 3) -
                         _tmp144 * covariance(1, 3) - _tmp145 * covariance(2, 3);
  const Scalar _tmp151 = _tmp56 * measurement_noise(2, 2) + _tmp62 * measurement_noise(0, 2) +
                         _tmp65 * measurement_noise(1, 2);
  const Scalar _tmp152 = _tmp56 * measurement_noise(2, 0) + _tmp62 * measurement_noise(0, 0) +
                         _tmp65 * measurement_noise(1, 0);
  const Scalar _tmp153 = -_tmp1 * _tmp93 - _tmp38 * _tmp95 + _tmp8 * _tmp94;
  const Scalar _tmp154 = _tmp1 * _tmp94 - _tmp37 * _tmp95 + _tmp8 * _tmp93;
  const Scalar _tmp155 = _tmp3 * _tmp93 + _tmp6 * _tmp94;
  const Scalar _tmp156 = _tmp3 * _tmp94 - _tmp6 * _tmp93;
  const Scalar _tmp157 = -_tmp153 * covariance(2, 3) - _tmp154 * covariance(1, 3) -
                         _tmp155 * covariance(3, 3) - _tmp156 * covariance(0, 3) + covariance(4, 3);
  const Scalar _tmp158 = -_tmp153 * covariance(2, 2) - _tmp154 * covariance(1, 2) -
                         _tmp155 * covariance(3, 2) - _tmp156 * covariance(0, 2) + covariance(4, 2);
  const Scalar _tmp159 = _tmp93 * measurement_noise(0, 0) + _tmp94 * measurement_noise(1, 0) +
                         _tmp95 * measurement_noise(2, 0);
  const Scalar _tmp160 = _tmp93 * measurement_noise(0, 2) + _tmp94 * measurement_noise(1, 2) +
                         _tmp95 * measurement_noise(2, 2);
  const Scalar _tmp161 = -_tmp153 * covariance(2, 0) - _tmp154 * covariance(1, 0) -
                         _tmp155 * covariance(3, 0) - _tmp156 * covariance(0, 0) + covariance(4, 0);
  const Scalar _tmp162 = _tmp93 * measurement_noise(0, 1) + _tmp94 * measurement_noise(1, 1) +
                         _tmp95 * measurement_noise(2, 1);
  const Scalar _tmp163 = -_tmp153 * covariance(2, 1) - _tmp154 * covariance(1, 1) -
                         _tmp155 * covariance(3, 1) - _tmp156 * covariance(0, 1) + covariance(4, 1);
  const Scalar _tmp164 = -_tmp1 * _tmp100 + _tmp101 * _tmp8 - _tmp38 * _tmp99;
  const Scalar _tmp165 = _tmp1 * _tmp101 + _tmp100 * _tmp8 - _tmp37 * _tmp99;
  const Scalar _tmp166 = _tmp100 * _tmp3 + _tmp101 * _tmp6;
  const Scalar _tmp167 = -_tmp100 * _tmp6 + _tmp101 * _tmp3;
  const Scalar _tmp168 = -_tmp164 * covariance(2, 3) - _tmp165 * covariance(1, 3) -
                         _tmp166 * covariance(3, 3) - _tmp167 * covariance(0, 3) + covariance(5, 3);
  const Scalar _tmp169 = -_tmp164 * covariance(2, 0) - _tmp165 * covariance(1, 0) -
                         _tmp166 * covariance(3, 0) - _tmp167 * covariance(0, 0) + covariance(5, 0);
  const Scalar _tmp170 = -_tmp164 * covariance(2, 1) - _tmp165 * covariance(1, 1) -
                         _tmp166 * covariance(3, 1) - _tmp167 * covariance(0, 1) + covariance(5, 1);
  const Scalar _tmp171 = _tmp100 * measurement_noise(0, 1) + _tmp101 * measurement_noise(1, 1) +
                         _tmp99 * measurement_noise(2, 1);
  const Scalar _tmp172 = _tmp100 * measurement_noise(0, 0) + _tmp101 * measurement_noise(1, 0) +
                         _tmp99 * measurement_noise(2, 0);
  const Scalar _tmp173 = -_tmp164 * covariance(2, 2) - _tmp165 * covariance(1, 2) -
                         _tmp166 * covariance(3, 2) - _tmp167 * covariance(0, 2) + covariance(5, 2);
  const Scalar _tmp174 = _tmp100 * measurement_noise(0, 2) + _tmp101 * measurement_noise(1, 2) +
                         _tmp99 * measurement_noise(2, 2);
  const Scalar _tmp175 = _tmp105 * _tmp3 + _tmp106 * _tmp6;
  const Scalar _tmp176 = -_tmp105 * _tmp6 + _tmp106 * _tmp3;
  const Scalar _tmp177 = _tmp0 * _tmp106;
  const Scalar _tmp178 = -_tmp1 * _tmp105 - _tmp107 * _tmp38 + _tmp177 * state(3, 0);
  const Scalar _tmp179 = _tmp105 * _tmp8 - _tmp107 * _tmp37 + _tmp177 * state(0, 0);
  const Scalar _tmp180 = -_tmp175 * covariance(3, 2) - _tmp176 * covariance(0, 2) -
                         _tmp178 * covariance(2, 2) - _tmp179 * covariance(1, 2) + covariance(6, 2);
  const Scalar _tmp181 = -_tmp175 * covariance(3, 3) - _tmp176 * covariance(0, 3) -
                         _tmp178 * covariance(2, 3) - _tmp179 * covariance(1, 3) + covariance(6, 3);
  const Scalar _tmp182 = _tmp105 * measurement_noise(0, 0) + _tmp106 * measurement_noise(1, 0) +
                         _tmp107 * measurement_noise(2, 0);
  const Scalar _tmp183 = _tmp105 * measurement_noise(0, 2) + _tmp106 * measurement_noise(1, 2) +
                         _tmp107 * measurement_noise(2, 2);
  const Scalar _tmp184 = _tmp105 * measurement_noise(0, 1) + _tmp106 * measurement_noise(1, 1) +
                         _tmp107 * measurement_noise(2, 1);
  const Scalar _tmp185 = -_tmp175 * covariance(3, 0) - _tmp176 * covariance(0, 0) -
                         _tmp178 * covariance(2, 0) - _tmp179 * covariance(1, 0) + covariance(6, 0);
  const Scalar _tmp186 = -_tmp175 * covariance(3, 1) - _tmp176 * covariance(0, 1) -
                         _tmp178 * covariance(2, 1) - _tmp179 * covariance(1, 1) + covariance(6, 1);

  // Output terms (2)
  if (new_state != nullptr) {
    Eigen::Matrix<Scalar, 7, 1>& _new_state = (*new_state);

    _new_state(0, 0) = _tmp81 * _tmp89;
    _new_state(1, 0) = _tmp88 * _tmp89;
    _new_state(2, 0) = _tmp74 * _tmp89;
    _new_state(3, 0) = _tmp67 * _tmp89;
    _new_state(4, 0) = _tmp57 * _tmp95 + _tmp58 * _tmp93 + _tmp66 * _tmp94 + state(4, 0);
    _new_state(5, 0) = _tmp100 * _tmp58 + _tmp101 * _tmp66 + _tmp57 * _tmp99 + state(5, 0);
    _new_state(6, 0) = _tmp105 * _tmp58 + _tmp106 * _tmp66 + _tmp107 * _tmp57 + state(6, 0);
  }

  if (new_covariance != nullptr) {
    Eigen::Matrix<Scalar, 7, 7>& _new_covariance = (*new_covariance);

    _new_covariance(0, 0) = _tmp108 * _tmp79 + _tmp109 * _tmp80 + _tmp110 * _tmp78 -
                            _tmp111 * _tmp115 + _tmp112 * _tmp118 - _tmp113 * _tmp116 -
                            _tmp114 * _tmp117;
    _new_covariance(1, 0) = -_tmp111 * _tmp129 + _tmp112 * _tmp123 - _tmp113 * _tmp124 -
                            _tmp114 * _tmp125 + _tmp126 * _tmp78 + _tmp127 * _tmp80 +
                            _tmp128 * _tmp79;
    _new_covariance(2, 0) = -_tmp111 * _tmp135 + _tmp112 * _tmp140 - _tmp113 * _tmp137 -
                            _tmp114 * _tmp138 + _tmp130 * _tmp80 + _tmp136 * _tmp79 +
                            _tmp139 * _tmp78;
    _new_covariance(3, 0) = -_tmp111 * _tmp150 + _tmp112 * _tmp146 - _tmp113 * _tmp148 -
                            _tmp114 * _tmp149 + _tmp147 * _tmp78 + _tmp151 * _tmp80 +
                            _tmp152 * _tmp79;
    _new_covariance(4, 0) = -_tmp111 * _tmp157 + _tmp112 * _tmp161 - _tmp113 * _tmp163 -
                            _tmp114 * _tmp158 + _tmp159 * _tmp79 + _tmp160 * _tmp80 +
                            _tmp162 * _tmp78;
    _new_covariance(5, 0) = -_tmp111 * _tmp168 + _tmp112 * _tmp169 - _tmp113 * _tmp170 -
                            _tmp114 * _tmp173 + _tmp171 * _tmp78 + _tmp172 * _tmp79 +
                            _tmp174 * _tmp80;
    _new_covariance(6, 0) = -_tmp111 * _tmp181 + _tmp112 * _tmp185 - _tmp113 * _tmp186 -
                            _tmp114 * _tmp180 + _tmp182 * _tmp79 + _tmp183 * _tmp80 +
                            _tmp184 * _tmp78;
    _new_covariance(0, 1) = _tmp108 * _tmp86 + _tmp109 * _tmp87 + _tmp110 * _tmp85 -
                            _tmp115 * _tmp122 + _tmp116 * _tmp120 - _tmp117 * _tmp119 -
                            _tmp118 * _tmp121;
    _new_covariance(1, 1) = -_tmp119 * _tmp125 + _tmp120 * _tmp124 - _tmp121 * _tmp123 -
                            _tmp122 * _tmp129 + _tmp126 * _tmp85 + _tmp127 * _tmp87 +
                            _tmp128 * _tmp86;
    _new_covariance(2, 1) = -_tmp119 * _tmp138 + _tmp120 * _tmp137 - _tmp121 * _tmp140 -
                            _tmp122 * _tmp135 + _tmp130 * _tmp87 + _tmp136 * _tmp86 +
                            _tmp139 * _tmp85;
    _new_covariance(3, 1) = -_tmp119 * _tmp149 + _tmp120 * _tmp148 - _tmp121 * _tmp146 -
                            _tmp122 * _tmp150 + _tmp147 * _tmp85 + _tmp151 * _tmp87 +
                            _tmp152 * _tmp86;
    _new_covariance(4, 1) = -_tmp119 * _tmp158 + _tmp120 * _tmp163 - _tmp121 * _tmp161 -
                            _tmp122 * _tmp157 + _tmp159 * _tmp86 + _tmp160 * _tmp87 +
                            _tmp162 * _tmp85;
    _new_covariance(5, 1) = -_tmp119 * _tmp173 + _tmp120 * _tmp170 - _tmp121 * _tmp169 -
                            _tmp122 * _tmp168 + _tmp171 * _tmp85 + _tmp172 * _tmp86 +
                            _tmp174 * _tmp87;
    _new_covariance(6, 1) = -_tmp119 * _tmp180 + _tmp120 * _tmp186 - _tmp121 * _tmp185 -
                            _tmp122 * _tmp181 + _tmp182 * _tmp86 + _tmp183 * _tmp87 +
                            _tmp184 * _tmp85;
    _new_covariance(0, 2) = _tmp108 * _tmp73 + _tmp109 * _tmp72 + _tmp110 * _tmp71 -
                            _tmp115 * _tmp134 - _tmp116 * _tmp131 + _tmp117 * _tmp132 -
                            _tmp118 * _tmp133;
    _new_covariance(1, 2) = -_tmp123 * _tmp133 - _tmp124 * _tmp131 + _tmp125 * _tmp132 +
                            _tmp126 * _tmp71 + _tmp127 * _tmp72 + _tmp128 * _tmp73 -
                            _tmp129 * _tmp134;
    _new_covariance(2, 2) = _tmp130 * _tmp72 - _tmp131 * _tmp137 + _tmp132 * _tmp138 -
                            _tmp133 * _tmp140 - _tmp134 * _tmp135 + _tmp136 * _tmp73 +
                            _tmp139 * _tmp71;
    _new_covariance(3, 2) = -_tmp131 * _tmp148 + _tmp132 * _tmp149 - _tmp133 * _tmp146 -
                            _tmp134 * _tmp150 + _tmp147 * _tmp71 + _tmp151 * _tmp72 +
                            _tmp152 * _tmp73;
    _new_covariance(4, 2) = -_tmp131 * _tmp163 + _tmp132 * _tmp158 - _tmp133 * _tmp161 -
                            _tmp134 * _tmp157 + _tmp159 * _tmp73 + _tmp160 * _tmp72 +
                            _tmp162 * _tmp71;
    _new_covariance(5, 2) = -_tmp131 * _tmp170 + _tmp132 * _tmp173 - _tmp133 * _tmp169 -
                            _tmp134 * _tmp168 + _tmp171 * _tmp71 + _tmp172 * _tmp73 +
                            _tmp174 * _tmp72;
    _new_covariance(6, 2) = -_tmp131 * _tmp186 + _tmp132 * _tmp180 - _tmp133 * _tmp185 -
                            _tmp134 * _tmp181 + _tmp182 * _tmp73 + _tmp183 * _tmp72 +
                            _tmp184 * _tmp71;
    _new_covariance(0, 3) = _tmp108 * _tmp62 + _tmp109 * _tmp56 + _tmp110 * _tmp65 +
                            _tmp115 * _tmp141 - _tmp116 * _tmp144 - _tmp117 * _tmp145 -
                            _tmp118 * _tmp142;
    _new_covariance(1, 3) = -_tmp123 * _tmp142 - _tmp124 * _tmp144 - _tmp125 * _tmp145 +
                            _tmp126 * _tmp65 + _tmp127 * _tmp56 + _tmp128 * _tmp62 +
                            _tmp129 * _tmp141;
    _new_covariance(2, 3) = _tmp130 * _tmp56 + _tmp135 * _tmp141 + _tmp136 * _tmp62 -
                            _tmp137 * _tmp144 - _tmp138 * _tmp145 + _tmp139 * _tmp65 -
                            _tmp140 * _tmp142;
    _new_covariance(3, 3) = _tmp141 * _tmp150 - _tmp142 * _tmp146 - _tmp144 * _tmp148 -
                            _tmp145 * _tmp149 + _tmp147 * _tmp65 + _tmp151 * _tmp56 +
                            _tmp152 * _tmp62;
    _new_covariance(4, 3) = _tmp141 * _tmp157 - _tmp142 * _tmp161 - _tmp144 * _tmp163 -
                            _tmp145 * _tmp158 + _tmp159 * _tmp62 + _tmp160 * _tmp56 +
                            _tmp162 * _tmp65;
    _new_covariance(5, 3) = _tmp141 * _tmp168 - _tmp142 * _tmp169 - _tmp144 * _tmp170 -
                            _tmp145 * _tmp173 + _tmp171 * _tmp65 + _tmp172 * _tmp62 +
                            _tmp174 * _tmp56;
    _new_covariance(6, 3) = _tmp141 * _tmp181 - _tmp142 * _tmp185 - _tmp144 * _tmp186 -
                            _tmp145 * _tmp180 + _tmp182 * _tmp62 + _tmp183 * _tmp56 +
                            _tmp184 * _tmp65;
    _new_covariance(0, 4) =
        _tmp108 * _tmp93 + _tmp109 * _tmp95 + _tmp110 * _tmp94 - _tmp111 * covariance(3, 4) +
        _tmp112 * covariance(0, 4) - _tmp113 * covariance(1, 4) - _tmp114 * covariance(2, 4) -
        _tmp115 * _tmp155 - _tmp116 * _tmp154 - _tmp117 * _tmp153 - _tmp118 * _tmp156;
    _new_covariance(1, 4) =
        -_tmp119 * covariance(2, 4) + _tmp120 * covariance(1, 4) - _tmp121 * covariance(0, 4) -
        _tmp122 * covariance(3, 4) - _tmp123 * _tmp156 - _tmp124 * _tmp154 - _tmp125 * _tmp153 +
        _tmp126 * _tmp94 + _tmp127 * _tmp95 + _tmp128 * _tmp93 - _tmp129 * _tmp155;
    _new_covariance(2, 4) = _tmp130 * _tmp95 - _tmp131 * covariance(1, 4) +
                            _tmp132 * covariance(2, 4) - _tmp133 * covariance(0, 4) -
                            _tmp134 * covariance(3, 4) - _tmp135 * _tmp155 + _tmp136 * _tmp93 -
                            _tmp137 * _tmp154 - _tmp138 * _tmp153 + _tmp139 * _tmp94 -
                            _tmp140 * _tmp156;
    _new_covariance(3, 4) =
        _tmp141 * covariance(3, 4) - _tmp142 * covariance(0, 4) - _tmp144 * covariance(1, 4) -
        _tmp145 * covariance(2, 4) - _tmp146 * _tmp156 + _tmp147 * _tmp94 - _tmp148 * _tmp154 -
        _tmp149 * _tmp153 - _tmp150 * _tmp155 + _tmp151 * _tmp95 + _tmp152 * _tmp93;
    _new_covariance(4, 4) = -_tmp153 * _tmp158 - _tmp153 * covariance(2, 4) - _tmp154 * _tmp163 -
                            _tmp154 * covariance(1, 4) - _tmp155 * _tmp157 -
                            _tmp155 * covariance(3, 4) - _tmp156 * _tmp161 -
                            _tmp156 * covariance(0, 4) + _tmp159 * _tmp93 + _tmp160 * _tmp95 +
                            _tmp162 * _tmp94 + covariance(4, 4);
    _new_covariance(5, 4) = -_tmp153 * _tmp173 - _tmp154 * _tmp170 - _tmp155 * _tmp168 -
                            _tmp156 * _tmp169 - _tmp164 * covariance(2, 4) -
                            _tmp165 * covariance(1, 4) - _tmp166 * covariance(3, 4) -
                            _tmp167 * covariance(0, 4) + _tmp171 * _tmp94 + _tmp172 * _tmp93 +
                            _tmp174 * _tmp95 + covariance(5, 4);
    _new_covariance(6, 4) = -_tmp153 * _tmp180 - _tmp154 * _tmp186 - _tmp155 * _tmp181 -
                            _tmp156 * _tmp185 - _tmp175 * covariance(3, 4) -
                            _tmp176 * covariance(0, 4) - _tmp178 * covariance(2, 4) -
                            _tmp179 * covariance(1, 4) + _tmp182 * _tmp93 + _tmp183 * _tmp95 +
                            _tmp184 * _tmp94 + covariance(6, 4);
    _new_covariance(0, 5) =
        _tmp100 * _tmp108 + _tmp101 * _tmp110 + _tmp109 * _tmp99 - _tmp111 * covariance(3, 5) +
        _tmp112 * covariance(0, 5) - _tmp113 * covariance(1, 5) - _tmp114 * covariance(2, 5) -
        _tmp115 * _tmp166 - _tmp116 * _tmp165 - _tmp117 * _tmp164 - _tmp118 * _tmp167;
    _new_covariance(1, 5) = _tmp100 * _tmp128 + _tmp101 * _tmp126 - _tmp119 * covariance(2, 5) +
                            _tmp120 * covariance(1, 5) - _tmp121 * covariance(0, 5) -
                            _tmp122 * covariance(3, 5) - _tmp123 * _tmp167 - _tmp124 * _tmp165 -
                            _tmp125 * _tmp164 + _tmp127 * _tmp99 - _tmp129 * _tmp166;
    _new_covariance(2, 5) =
        _tmp100 * _tmp136 + _tmp101 * _tmp139 + _tmp130 * _tmp99 - _tmp131 * covariance(1, 5) +
        _tmp132 * covariance(2, 5) - _tmp133 * covariance(0, 5) - _tmp134 * covariance(3, 5) -
        _tmp135 * _tmp166 - _tmp137 * _tmp165 - _tmp138 * _tmp164 - _tmp140 * _tmp167;
    _new_covariance(3, 5) = _tmp100 * _tmp152 + _tmp101 * _tmp147 + _tmp141 * covariance(3, 5) -
                            _tmp142 * covariance(0, 5) - _tmp144 * covariance(1, 5) -
                            _tmp145 * covariance(2, 5) - _tmp146 * _tmp167 - _tmp148 * _tmp165 -
                            _tmp149 * _tmp164 - _tmp150 * _tmp166 + _tmp151 * _tmp99;
    _new_covariance(4, 5) = _tmp100 * _tmp159 + _tmp101 * _tmp162 - _tmp153 * covariance(2, 5) -
                            _tmp154 * covariance(1, 5) - _tmp155 * covariance(3, 5) -
                            _tmp156 * covariance(0, 5) - _tmp157 * _tmp166 - _tmp158 * _tmp164 +
                            _tmp160 * _tmp99 - _tmp161 * _tmp167 - _tmp163 * _tmp165 +
                            covariance(4, 5);
    _new_covariance(5, 5) = _tmp100 * _tmp172 + _tmp101 * _tmp171 - _tmp164 * _tmp173 -
                            _tmp164 * covariance(2, 5) - _tmp165 * _tmp170 -
                            _tmp165 * covariance(1, 5) - _tmp166 * _tmp168 -
                            _tmp166 * covariance(3, 5) - _tmp167 * _tmp169 -
                            _tmp167 * covariance(0, 5) + _tmp174 * _tmp99 + covariance(5, 5);
    _new_covariance(6, 5) = _tmp100 * _tmp182 + _tmp101 * _tmp184 - _tmp164 * _tmp180 -
                            _tmp165 * _tmp186 - _tmp166 * _tmp181 - _tmp167 * _tmp185 -
                            _tmp175 * covariance(3, 5) - _tmp176 * covariance(0, 5) -
                            _tmp178 * covariance(2, 5) - _tmp179 * covariance(1, 5) +
                            _tmp183 * _tmp99 + covariance(6, 5);
    _new_covariance(0, 6) =
        _tmp105 * _tmp108 + _tmp106 * _tmp110 + _tmp107 * _tmp109 - _tmp111 * covariance(3, 6) +
        _tmp112 * covariance(0, 6) - _tmp113 * covariance(1, 6) - _tmp114 * covariance(2, 6) -
        _tmp115 * _tmp175 - _tmp116 * _tmp179 - _tmp117 * _tmp178 - _tmp118 * _tmp176;
    _new_covariance(1, 6) =
        _tmp105 * _tmp128 + _tmp106 * _tmp126 + _tmp107 * _tmp127 - _tmp119 * covariance(2, 6) +
        _tmp120 * covariance(1, 6) - _tmp121 * covariance(0, 6) - _tmp122 * covariance(3, 6) -
        _tmp123 * _tmp176 - _tmp124 * _tmp179 - _tmp125 * _tmp178 - _tmp129 * _tmp175;
    _new_covariance(2, 6) =
        _tmp105 * _tmp136 + _tmp106 * _tmp139 + _tmp107 * _tmp130 - _tmp131 * covariance(1, 6) +
        _tmp132 * covariance(2, 6) - _tmp133 * covariance(0, 6) - _tmp134 * covariance(3, 6) -
        _tmp135 * _tmp175 - _tmp137 * _tmp179 - _tmp138 * _tmp178 - _tmp140 * _tmp176;
    _new_covariance(3, 6) =
        _tmp105 * _tmp152 + _tmp106 * _tmp147 + _tmp107 * _tmp151 + _tmp141 * covariance(3, 6) -
        _tmp142 * covariance(0, 6) - _tmp144 * covariance(1, 6) - _tmp145 * covariance(2, 6) -
        _tmp146 * _tmp176 - _tmp148 * _tmp179 - _tmp149 * _tmp178 - _tmp150 * _tmp175;
    _new_covariance(4, 6) = _tmp105 * _tmp159 + _tmp106 * _tmp162 + _tmp107 * _tmp160 -
                            _tmp153 * covariance(2, 6) - _tmp154 * covariance(1, 6) -
                            _tmp155 * covariance(3, 6) - _tmp156 * covariance(0, 6) -
                            _tmp157 * _tmp175 - _tmp158 * _tmp178 - _tmp161 * _tmp176 -
                            _tmp163 * _tmp179 + covariance(4, 6);
    _new_covariance(5, 6) = _tmp105 * _tmp172 + _tmp106 * _tmp171 + _tmp107 * _tmp174 -
                            _tmp164 * covariance(2, 6) - _tmp165 * covariance(1, 6) -
                            _tmp166 * covariance(3, 6) - _tmp167 * covariance(0, 6) -
                            _tmp168 * _tmp175 - _tmp169 * _tmp176 - _tmp170 * _tmp179 -
                            _tmp173 * _tmp178 + covariance(5, 6);
    _new_covariance(6, 6) = _tmp105 * _tmp182 + _tmp106 * _tmp184 + _tmp107 * _tmp183 -
                            _tmp175 * _tmp181 - _tmp175 * covariance(3, 6) - _tmp176 * _tmp185 -
                            _tmp176 * covariance(0, 6) - _tmp178 * _tmp180 -
                            _tmp178 * covariance(2, 6) - _tmp179 * _tmp186 -
                            _tmp179 * covariance(1, 6) + covariance(6, 6);
  }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
