// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

namespace sym {

/**
 * Symbolic update function.
 */
template <typename Scalar>
void Update(const Eigen::Matrix<Scalar, 7, 1>& state, const Eigen::Matrix<Scalar, 7, 7>& covariance,
            const Eigen::Matrix<Scalar, 6, 1>& measurement,
            const Eigen::Matrix<Scalar, 6, 6>& measurement_noise,
            Eigen::Matrix<Scalar, 7, 1>* const new_state = nullptr,
            Eigen::Matrix<Scalar, 7, 7>* const new_covariance = nullptr) {
  // Total ops: 3731

  // Input arrays

  // Intermediate terms (349)
  const Scalar _tmp0 = measurement(2, 0) - state(6, 0);
  const Scalar _tmp1 = 4 * state(2, 0);
  const Scalar _tmp2 = 4 * state(3, 0);
  const Scalar _tmp3 = -_tmp1 * covariance(4, 2) - _tmp2 * covariance(4, 3);
  const Scalar _tmp4 = _tmp3 + measurement_noise(0, 3);
  const Scalar _tmp5 = Scalar(1.0) / (covariance(4, 4) + measurement_noise(0, 0));
  const Scalar _tmp6 = _tmp5 * (covariance(5, 4) + measurement_noise(1, 0));
  const Scalar _tmp7 = -_tmp1 * covariance(5, 2) - _tmp2 * covariance(5, 3);
  const Scalar _tmp8 = -_tmp4 * _tmp6 + _tmp7 + measurement_noise(1, 3);
  const Scalar _tmp9 = -_tmp1 * covariance(2, 2);
  const Scalar _tmp10 = -_tmp2 * covariance(3, 2) + _tmp9;
  const Scalar _tmp11 = -_tmp2 * covariance(3, 3);
  const Scalar _tmp12 = -_tmp1 * covariance(2, 3) + _tmp11;
  const Scalar _tmp13 =
      _tmp5 * (-_tmp1 * covariance(2, 4) - _tmp2 * covariance(3, 4) + measurement_noise(3, 0));
  const Scalar _tmp14 = covariance(4, 5) + measurement_noise(0, 1);
  const Scalar _tmp15 =
      Scalar(1.0) / (-_tmp14 * _tmp6 + covariance(5, 5) + measurement_noise(1, 1));
  const Scalar _tmp16 = _tmp15 * (-_tmp1 * covariance(2, 5) - _tmp13 * _tmp14 -
                                  _tmp2 * covariance(3, 5) + measurement_noise(3, 1));
  const Scalar _tmp17 = _tmp5 * (covariance(6, 4) + measurement_noise(2, 0));
  const Scalar _tmp18 = _tmp15 * (-_tmp14 * _tmp17 + covariance(6, 5) + measurement_noise(2, 1));
  const Scalar _tmp19 = -_tmp1 * covariance(6, 2) - _tmp2 * covariance(6, 3);
  const Scalar _tmp20 = -_tmp17 * _tmp4 - _tmp18 * _tmp8 + _tmp19 + measurement_noise(2, 3);
  const Scalar _tmp21 = covariance(4, 6) + measurement_noise(0, 2);
  const Scalar _tmp22 = -_tmp21 * _tmp6 + covariance(5, 6) + measurement_noise(1, 2);
  const Scalar _tmp23 = Scalar(1.0) / (-_tmp17 * _tmp21 - _tmp18 * _tmp22 + covariance(6, 6) +
                                       measurement_noise(2, 2));
  const Scalar _tmp24 = _tmp23 * (-_tmp1 * covariance(2, 6) - _tmp13 * _tmp21 - _tmp16 * _tmp22 -
                                  _tmp2 * covariance(3, 6) + measurement_noise(3, 2));
  const Scalar _tmp25 = Scalar(1.0) / (-_tmp1 * _tmp10 - _tmp12 * _tmp2 - _tmp13 * _tmp4 -
                                       _tmp16 * _tmp8 - _tmp20 * _tmp24 + measurement_noise(3, 3));
  const Scalar _tmp26 = 2 * state(2, 0);
  const Scalar _tmp27 = 2 * state(3, 0);
  const Scalar _tmp28 = 2 * state(1, 0);
  const Scalar _tmp29 = 2 * state(0, 0);
  const Scalar _tmp30 =
      _tmp5 * (_tmp26 * covariance(1, 4) + _tmp27 * covariance(0, 4) + _tmp28 * covariance(2, 4) +
               _tmp29 * covariance(3, 4) + measurement_noise(4, 0));
  const Scalar _tmp31 =
      _tmp15 * (-_tmp14 * _tmp30 + _tmp26 * covariance(1, 5) + _tmp27 * covariance(0, 5) +
                _tmp28 * covariance(2, 5) + _tmp29 * covariance(3, 5) + measurement_noise(4, 1));
  const Scalar _tmp32 = _tmp23 * (-_tmp21 * _tmp30 - _tmp22 * _tmp31 + _tmp26 * covariance(1, 6) +
                                  _tmp27 * covariance(0, 6) + _tmp28 * covariance(2, 6) +
                                  _tmp29 * covariance(3, 6) + measurement_noise(4, 2));
  const Scalar _tmp33 = 2 * covariance(1, 3);
  const Scalar _tmp34 = _tmp28 * covariance(2, 3);
  const Scalar _tmp35 = _tmp29 * covariance(3, 3);
  const Scalar _tmp36 = _tmp27 * covariance(0, 3) + _tmp33 * state(2, 0) + _tmp34 + _tmp35;
  const Scalar _tmp37 = _tmp28 * covariance(2, 2);
  const Scalar _tmp38 = _tmp29 * covariance(3, 2);
  const Scalar _tmp39 = _tmp26 * covariance(1, 2) + _tmp27 * covariance(0, 2) + _tmp37 + _tmp38;
  const Scalar _tmp40 = _tmp25 * (-_tmp1 * _tmp39 - _tmp2 * _tmp36 - _tmp20 * _tmp32 -
                                  _tmp30 * _tmp4 - _tmp31 * _tmp8 + measurement_noise(4, 3));
  const Scalar _tmp41 = _tmp24 * _tmp40 - _tmp32;
  const Scalar _tmp42 = _tmp26 * covariance(4, 1) + _tmp27 * covariance(4, 0) +
                        _tmp28 * covariance(4, 2) + _tmp29 * covariance(4, 3);
  const Scalar _tmp43 = _tmp42 + measurement_noise(0, 4);
  const Scalar _tmp44 = 2 * covariance(5, 0);
  const Scalar _tmp45 = _tmp26 * covariance(5, 1) + _tmp28 * covariance(5, 2) +
                        _tmp29 * covariance(5, 3) + _tmp44 * state(3, 0);
  const Scalar _tmp46 = -_tmp43 * _tmp6 + _tmp45 + measurement_noise(1, 4);
  const Scalar _tmp47 = _tmp26 * covariance(1, 0);
  const Scalar _tmp48 = _tmp27 * covariance(0, 0);
  const Scalar _tmp49 = _tmp28 * covariance(2, 0) + _tmp29 * covariance(3, 0) + _tmp47 + _tmp48;
  const Scalar _tmp50 = _tmp26 * covariance(1, 1);
  const Scalar _tmp51 = _tmp27 * covariance(0, 1);
  const Scalar _tmp52 = _tmp28 * covariance(2, 1) + _tmp29 * covariance(3, 1) + _tmp50 + _tmp51;
  const Scalar _tmp53 = -_tmp1 * covariance(2, 0) - _tmp2 * covariance(3, 0);
  const Scalar _tmp54 = -_tmp1 * covariance(2, 1) - _tmp2 * covariance(3, 1);
  const Scalar _tmp55 = _tmp26 * covariance(6, 1) + _tmp27 * covariance(6, 0) +
                        _tmp28 * covariance(6, 2) + _tmp29 * covariance(6, 3);
  const Scalar _tmp56 = -_tmp17 * _tmp43 - _tmp18 * _tmp46 + _tmp55 + measurement_noise(2, 4);
  const Scalar _tmp57 = _tmp10 * _tmp28 + _tmp12 * _tmp29 - _tmp13 * _tmp43 - _tmp16 * _tmp46 -
                        _tmp24 * _tmp56 + _tmp26 * _tmp54 + _tmp27 * _tmp53 +
                        measurement_noise(3, 4);
  const Scalar _tmp58 = Scalar(1.0) / (_tmp26 * _tmp52 + _tmp27 * _tmp49 + _tmp28 * _tmp39 +
                                       _tmp29 * _tmp36 - _tmp30 * _tmp43 - _tmp31 * _tmp46 -
                                       _tmp32 * _tmp56 - _tmp40 * _tmp57 + measurement_noise(4, 4));
  const Scalar _tmp59 =
      _tmp5 * (-_tmp26 * covariance(0, 4) + _tmp27 * covariance(1, 4) + _tmp28 * covariance(3, 4) -
               _tmp29 * covariance(2, 4) + measurement_noise(5, 0));
  const Scalar _tmp60 =
      _tmp15 * (-_tmp14 * _tmp59 - _tmp26 * covariance(0, 5) + _tmp27 * covariance(1, 5) +
                _tmp28 * covariance(3, 5) - _tmp29 * covariance(2, 5) + measurement_noise(5, 1));
  const Scalar _tmp61 = _tmp29 * covariance(2, 3);
  const Scalar _tmp62 = _tmp28 * covariance(3, 3);
  const Scalar _tmp63 = -_tmp26 * covariance(0, 3) + _tmp33 * state(3, 0) - _tmp61 + _tmp62;
  const Scalar _tmp64 = -_tmp29 * covariance(2, 2);
  const Scalar _tmp65 = _tmp28 * covariance(3, 2);
  const Scalar _tmp66 = -_tmp26 * covariance(0, 2) + _tmp27 * covariance(1, 2) + _tmp64 + _tmp65;
  const Scalar _tmp67 = _tmp23 * (-_tmp21 * _tmp59 - _tmp22 * _tmp60 - _tmp26 * covariance(0, 6) +
                                  _tmp27 * covariance(1, 6) + _tmp28 * covariance(3, 6) -
                                  _tmp29 * covariance(2, 6) + measurement_noise(5, 2));
  const Scalar _tmp68 = _tmp25 * (-_tmp1 * _tmp66 - _tmp2 * _tmp63 - _tmp20 * _tmp67 -
                                  _tmp4 * _tmp59 - _tmp60 * _tmp8 + measurement_noise(5, 3));
  const Scalar _tmp69 = _tmp27 * covariance(1, 0);
  const Scalar _tmp70 = -_tmp26 * covariance(0, 0);
  const Scalar _tmp71 = _tmp28 * covariance(3, 0) - _tmp29 * covariance(2, 0) + _tmp69 + _tmp70;
  const Scalar _tmp72 = _tmp27 * covariance(1, 1);
  const Scalar _tmp73 = _tmp26 * covariance(0, 1);
  const Scalar _tmp74 = _tmp28 * covariance(3, 1) - _tmp29 * covariance(2, 1) + _tmp72 - _tmp73;
  const Scalar _tmp75 = _tmp58 * (_tmp26 * _tmp74 + _tmp27 * _tmp71 + _tmp28 * _tmp66 +
                                  _tmp29 * _tmp63 - _tmp43 * _tmp59 - _tmp46 * _tmp60 -
                                  _tmp56 * _tmp67 - _tmp57 * _tmp68 + measurement_noise(5, 4));
  const Scalar _tmp76 = _tmp24 * _tmp68 - _tmp41 * _tmp75 - _tmp67;
  const Scalar _tmp77 = -_tmp26 * covariance(4, 0) + _tmp27 * covariance(4, 1) +
                        _tmp28 * covariance(4, 3) - _tmp29 * covariance(4, 2);
  const Scalar _tmp78 = _tmp77 + measurement_noise(0, 5);
  const Scalar _tmp79 = _tmp27 * covariance(5, 1) + _tmp28 * covariance(5, 3) -
                        _tmp29 * covariance(5, 2) - _tmp44 * state(2, 0);
  const Scalar _tmp80 = -_tmp6 * _tmp78 + _tmp79 + measurement_noise(1, 5);
  const Scalar _tmp81 = -_tmp26 * covariance(6, 0) + _tmp27 * covariance(6, 1) +
                        _tmp28 * covariance(6, 3) - _tmp29 * covariance(6, 2);
  const Scalar _tmp82 = -_tmp17 * _tmp78 - _tmp18 * _tmp80 + _tmp81 + measurement_noise(2, 5);
  const Scalar _tmp83 = -_tmp10 * _tmp29 + _tmp12 * _tmp28 - _tmp13 * _tmp78 - _tmp16 * _tmp80 -
                        _tmp24 * _tmp82 - _tmp26 * _tmp53 + _tmp27 * _tmp54 +
                        measurement_noise(3, 5);
  const Scalar _tmp84 = -_tmp26 * _tmp49 + _tmp27 * _tmp52 + _tmp28 * _tmp36 - _tmp29 * _tmp39 -
                        _tmp30 * _tmp78 - _tmp31 * _tmp80 - _tmp32 * _tmp82 - _tmp40 * _tmp83 +
                        measurement_noise(4, 5);
  const Scalar _tmp85 =
      Scalar(1.0) / (-_tmp26 * _tmp71 + _tmp27 * _tmp74 + _tmp28 * _tmp63 - _tmp29 * _tmp66 -
                     _tmp59 * _tmp78 - _tmp60 * _tmp80 - _tmp67 * _tmp82 - _tmp68 * _tmp83 -
                     _tmp75 * _tmp84 + measurement_noise(5, 5));
  const Scalar _tmp86 = _tmp83 * _tmp85;
  const Scalar _tmp87 = _tmp84 * _tmp85;
  const Scalar _tmp88 = _tmp41 - _tmp76 * _tmp87;
  const Scalar _tmp89 = _tmp57 * _tmp58;
  const Scalar _tmp90 = _tmp25 * (-_tmp24 - _tmp76 * _tmp86 - _tmp88 * _tmp89);
  const Scalar _tmp91 = _tmp82 * _tmp85;
  const Scalar _tmp92 = _tmp58 * _tmp88;
  const Scalar _tmp93 = -_tmp20 * _tmp90 - _tmp56 * _tmp92 - _tmp76 * _tmp91 + 1;
  const Scalar _tmp94 = _tmp23 * _tmp93;
  const Scalar _tmp95 = _tmp80 * _tmp85;
  const Scalar _tmp96 = -_tmp22 * _tmp94 - _tmp46 * _tmp92 - _tmp76 * _tmp95 - _tmp8 * _tmp90;
  const Scalar _tmp97 = _tmp15 * covariance(0, 5);
  const Scalar _tmp98 = _tmp15 * _tmp96;
  const Scalar _tmp99 = _tmp78 * _tmp85;
  const Scalar _tmp100 = _tmp21 * _tmp23;
  const Scalar _tmp101 =
      -_tmp100 * _tmp93 - _tmp14 * _tmp98 - _tmp4 * _tmp90 - _tmp43 * _tmp92 - _tmp76 * _tmp99;
  const Scalar _tmp102 = _tmp101 * _tmp5;
  const Scalar _tmp103 = _tmp28 * covariance(0, 2) + _tmp29 * covariance(0, 3) + _tmp48 + _tmp73;
  const Scalar _tmp104 =
      _tmp85 * (_tmp28 * covariance(0, 3) - _tmp29 * covariance(0, 2) + _tmp51 + _tmp70);
  const Scalar _tmp105 = -_tmp1 * covariance(0, 2) - _tmp2 * covariance(0, 3);
  const Scalar _tmp106 = _tmp102 * covariance(0, 4) + _tmp103 * _tmp92 + _tmp104 * _tmp76 +
                         _tmp105 * _tmp90 + _tmp94 * covariance(0, 6) + _tmp96 * _tmp97;
  const Scalar _tmp107 = measurement(0, 0) - state(4, 0);
  const Scalar _tmp108 = -_tmp17 + _tmp18 * _tmp6;
  const Scalar _tmp109 = -_tmp108 * _tmp24 - _tmp13 + _tmp16 * _tmp6;
  const Scalar _tmp110 = -_tmp108 * _tmp32 - _tmp109 * _tmp40 - _tmp30 + _tmp31 * _tmp6;
  const Scalar _tmp111 =
      -_tmp108 * _tmp67 - _tmp109 * _tmp68 - _tmp110 * _tmp75 - _tmp59 + _tmp6 * _tmp60;
  const Scalar _tmp112 = _tmp110 - _tmp111 * _tmp87;
  const Scalar _tmp113 = _tmp112 * _tmp58;
  const Scalar _tmp114 = _tmp109 - _tmp111 * _tmp86 - _tmp112 * _tmp89;
  const Scalar _tmp115 = _tmp114 * _tmp25;
  const Scalar _tmp116 =
      _tmp23 * (_tmp108 - _tmp111 * _tmp91 - _tmp113 * _tmp56 - _tmp115 * _tmp20);
  const Scalar _tmp117 =
      -_tmp111 * _tmp95 - _tmp113 * _tmp46 - _tmp115 * _tmp8 - _tmp116 * _tmp22 - _tmp6;
  const Scalar _tmp118 = _tmp117 * _tmp15;
  const Scalar _tmp119 = _tmp5 * (-_tmp111 * _tmp99 - _tmp113 * _tmp43 - _tmp115 * _tmp4 -
                                  _tmp116 * _tmp21 - _tmp118 * _tmp14 + 1);
  const Scalar _tmp120 = _tmp103 * _tmp113 + _tmp104 * _tmp111 + _tmp105 * _tmp115 +
                         _tmp116 * covariance(0, 6) + _tmp117 * _tmp97 + _tmp119 * covariance(0, 4);
  const Scalar _tmp121 = _tmp75 * _tmp87 + 1;
  const Scalar _tmp122 = _tmp121 * _tmp58;
  const Scalar _tmp123 = -_tmp121 * _tmp89 + _tmp75 * _tmp86;
  const Scalar _tmp124 = _tmp123 * _tmp25;
  const Scalar _tmp125 = _tmp23 * (-_tmp122 * _tmp56 - _tmp124 * _tmp20 + _tmp75 * _tmp91);
  const Scalar _tmp126 = -_tmp122 * _tmp46 - _tmp124 * _tmp8 - _tmp125 * _tmp22 + _tmp75 * _tmp95;
  const Scalar _tmp127 = _tmp126 * _tmp15;
  const Scalar _tmp128 =
      -_tmp122 * _tmp43 - _tmp124 * _tmp4 - _tmp125 * _tmp21 - _tmp127 * _tmp14 + _tmp75 * _tmp99;
  const Scalar _tmp129 = _tmp128 * _tmp5;
  const Scalar _tmp130 = _tmp103 * _tmp122 - _tmp104 * _tmp75 + _tmp105 * _tmp124 +
                         _tmp125 * covariance(0, 6) + _tmp126 * _tmp97 + _tmp129 * covariance(0, 4);
  const Scalar _tmp131 = -_tmp28 * state(2, 0) - _tmp29 * state(3, 0) + measurement(4, 0);
  const Scalar _tmp132 = -_tmp86 + _tmp87 * _tmp89;
  const Scalar _tmp133 = _tmp132 * _tmp25;
  const Scalar _tmp134 = _tmp58 * _tmp87;
  const Scalar _tmp135 = -_tmp133 * _tmp20 + _tmp134 * _tmp56 - _tmp91;
  const Scalar _tmp136 = _tmp135 * _tmp23;
  const Scalar _tmp137 = -_tmp133 * _tmp8 + _tmp134 * _tmp46 - _tmp136 * _tmp22 - _tmp95;
  const Scalar _tmp138 = _tmp137 * _tmp15;
  const Scalar _tmp139 =
      -_tmp100 * _tmp135 - _tmp133 * _tmp4 + _tmp134 * _tmp43 - _tmp138 * _tmp14 - _tmp99;
  const Scalar _tmp140 = _tmp139 * _tmp5;
  const Scalar _tmp141 = -_tmp103 * _tmp134 + _tmp104 + _tmp105 * _tmp133 +
                         _tmp136 * covariance(0, 6) + _tmp137 * _tmp97 + _tmp140 * covariance(0, 4);
  const Scalar _tmp142 = -_tmp28 * state(3, 0) + _tmp29 * state(2, 0) + measurement(5, 0);
  const Scalar _tmp143 = measurement(1, 0) - state(5, 0);
  const Scalar _tmp144 = -_tmp16 + _tmp18 * _tmp24;
  const Scalar _tmp145 = -_tmp144 * _tmp40 + _tmp18 * _tmp32 - _tmp31;
  const Scalar _tmp146 = -_tmp144 * _tmp68 - _tmp145 * _tmp75 + _tmp18 * _tmp67 - _tmp60;
  const Scalar _tmp147 = _tmp145 - _tmp146 * _tmp87;
  const Scalar _tmp148 = _tmp25 * (_tmp144 - _tmp146 * _tmp86 - _tmp147 * _tmp89);
  const Scalar _tmp149 = _tmp147 * _tmp58;
  const Scalar _tmp150 = -_tmp146 * _tmp91 - _tmp148 * _tmp20 - _tmp149 * _tmp56 - _tmp18;
  const Scalar _tmp151 = _tmp150 * _tmp23;
  const Scalar _tmp152 =
      -_tmp146 * _tmp95 - _tmp148 * _tmp8 - _tmp149 * _tmp46 - _tmp151 * _tmp22 + 1;
  const Scalar _tmp153 = _tmp15 * _tmp152;
  const Scalar _tmp154 =
      -_tmp100 * _tmp150 - _tmp14 * _tmp153 - _tmp146 * _tmp99 - _tmp148 * _tmp4 - _tmp149 * _tmp43;
  const Scalar _tmp155 = _tmp154 * _tmp5;
  const Scalar _tmp156 = _tmp103 * _tmp149 + _tmp104 * _tmp146 + _tmp105 * _tmp148 +
                         _tmp151 * covariance(0, 6) + _tmp152 * _tmp97 + _tmp155 * covariance(0, 4);
  const Scalar _tmp157 = _tmp40 * _tmp75 - _tmp68;
  const Scalar _tmp158 = -_tmp157 * _tmp87 - _tmp40;
  const Scalar _tmp159 = _tmp25 * (-_tmp157 * _tmp86 - _tmp158 * _tmp89 + 1);
  const Scalar _tmp160 = _tmp158 * _tmp58;
  const Scalar _tmp161 = _tmp23 * (-_tmp157 * _tmp91 - _tmp159 * _tmp20 - _tmp160 * _tmp56);
  const Scalar _tmp162 = -_tmp157 * _tmp95 - _tmp159 * _tmp8 - _tmp160 * _tmp46 - _tmp161 * _tmp22;
  const Scalar _tmp163 = _tmp15 * _tmp162;
  const Scalar _tmp164 = _tmp5 * (-_tmp14 * _tmp163 - _tmp157 * _tmp99 - _tmp159 * _tmp4 -
                                  _tmp160 * _tmp43 - _tmp161 * _tmp21);
  const Scalar _tmp165 = _tmp103 * _tmp160 + _tmp104 * _tmp157 + _tmp105 * _tmp159 +
                         _tmp161 * covariance(0, 6) + _tmp162 * _tmp97 + _tmp164 * covariance(0, 4);
  const Scalar _tmp166 = measurement(3, 0) + 2 * std::pow(state(2, 0), Scalar(2)) +
                         2 * std::pow(state(3, 0), Scalar(2)) - 1;
  const Scalar _tmp167 = _tmp0 * _tmp106 + _tmp107 * _tmp120 + _tmp130 * _tmp131 +
                         _tmp141 * _tmp142 + _tmp143 * _tmp156 + _tmp165 * _tmp166 + state(0, 0);
  const Scalar _tmp168 =
      _tmp85 * (_tmp28 * covariance(1, 3) - _tmp29 * covariance(1, 2) - _tmp47 + _tmp72);
  const Scalar _tmp169 = _tmp28 * covariance(1, 2) + _tmp33 * state(0, 0) + _tmp50 + _tmp69;
  const Scalar _tmp170 = -_tmp1 * covariance(1, 2) - _tmp2 * covariance(1, 3);
  const Scalar _tmp171 = _tmp122 * _tmp169 + _tmp124 * _tmp170 + _tmp125 * covariance(1, 6) +
                         _tmp127 * covariance(1, 5) + _tmp129 * covariance(1, 4) - _tmp168 * _tmp75;
  const Scalar _tmp172 = _tmp146 * _tmp168 + _tmp148 * _tmp170 + _tmp149 * _tmp169 +
                         _tmp151 * covariance(1, 6) + _tmp153 * covariance(1, 5) +
                         _tmp155 * covariance(1, 4);
  const Scalar _tmp173 = _tmp133 * _tmp170 - _tmp134 * _tmp169 + _tmp136 * covariance(1, 6) +
                         _tmp138 * covariance(1, 5) + _tmp140 * covariance(1, 4) + _tmp168;
  const Scalar _tmp174 = _tmp102 * covariance(1, 4) + _tmp168 * _tmp76 + _tmp169 * _tmp92 +
                         _tmp170 * _tmp90 + _tmp94 * covariance(1, 6) + _tmp98 * covariance(1, 5);
  const Scalar _tmp175 = _tmp157 * _tmp168 + _tmp159 * _tmp170 + _tmp160 * _tmp169 +
                         _tmp161 * covariance(1, 6) + _tmp163 * covariance(1, 5) +
                         _tmp164 * covariance(1, 4);
  const Scalar _tmp176 = _tmp111 * _tmp168 + _tmp113 * _tmp169 + _tmp115 * _tmp170 +
                         _tmp116 * covariance(1, 6) + _tmp118 * covariance(1, 5) +
                         _tmp119 * covariance(1, 4);
  const Scalar _tmp177 = _tmp0 * _tmp174 + _tmp107 * _tmp176 + _tmp131 * _tmp171 +
                         _tmp142 * _tmp173 + _tmp143 * _tmp172 + _tmp166 * _tmp175 + state(1, 0);
  const Scalar _tmp178 = -_tmp2 * covariance(2, 3) + _tmp9;
  const Scalar _tmp179 = _tmp26 * covariance(2, 1) + _tmp27 * covariance(2, 0) + _tmp37 + _tmp61;
  const Scalar _tmp180 =
      _tmp85 * (-_tmp26 * covariance(2, 0) + _tmp27 * covariance(2, 1) + _tmp34 + _tmp64);
  const Scalar _tmp181 = _tmp122 * _tmp179 + _tmp124 * _tmp178 + _tmp125 * covariance(2, 6) +
                         _tmp127 * covariance(2, 5) + _tmp129 * covariance(2, 4) - _tmp180 * _tmp75;
  const Scalar _tmp182 = _tmp111 * _tmp180 + _tmp113 * _tmp179 + _tmp115 * _tmp178 +
                         _tmp116 * covariance(2, 6) + _tmp118 * covariance(2, 5) +
                         _tmp119 * covariance(2, 4);
  const Scalar _tmp183 = _tmp102 * covariance(2, 4) + _tmp178 * _tmp90 + _tmp179 * _tmp92 +
                         _tmp180 * _tmp76 + _tmp94 * covariance(2, 6) + _tmp98 * covariance(2, 5);
  const Scalar _tmp184 = _tmp157 * _tmp180 + _tmp159 * _tmp178 + _tmp160 * _tmp179 +
                         _tmp161 * covariance(2, 6) + _tmp163 * covariance(2, 5) +
                         _tmp164 * covariance(2, 4);
  const Scalar _tmp185 = _tmp146 * _tmp180 + _tmp148 * _tmp178 + _tmp149 * _tmp179 +
                         _tmp151 * covariance(2, 6) + _tmp153 * covariance(2, 5) +
                         _tmp155 * covariance(2, 4);
  const Scalar _tmp186 = _tmp133 * _tmp178 - _tmp134 * _tmp179 + _tmp136 * covariance(2, 6) +
                         _tmp138 * covariance(2, 5) + _tmp140 * covariance(2, 4) + _tmp180;
  const Scalar _tmp187 = _tmp0 * _tmp183 + _tmp107 * _tmp182 + _tmp131 * _tmp181 +
                         _tmp142 * _tmp186 + _tmp143 * _tmp185 + _tmp166 * _tmp184 + state(2, 0);
  const Scalar _tmp188 =
      _tmp85 * (-_tmp26 * covariance(3, 0) + _tmp27 * covariance(3, 1) - _tmp38 + _tmp62);
  const Scalar _tmp189 = _tmp26 * covariance(3, 1) + _tmp27 * covariance(3, 0) + _tmp35 + _tmp65;
  const Scalar _tmp190 = _tmp189 * _tmp58;
  const Scalar _tmp191 = -_tmp1 * covariance(3, 2) + _tmp11;
  const Scalar _tmp192 = _tmp102 * covariance(3, 4) + _tmp188 * _tmp76 + _tmp190 * _tmp88 +
                         _tmp191 * _tmp90 + _tmp94 * covariance(3, 6) + _tmp98 * covariance(3, 5);
  const Scalar _tmp193 = _tmp133 * _tmp191 + _tmp136 * covariance(3, 6) +
                         _tmp138 * covariance(3, 5) + _tmp140 * covariance(3, 4) + _tmp188 -
                         _tmp190 * _tmp87;
  const Scalar _tmp194 = _tmp121 * _tmp190 + _tmp124 * _tmp191 + _tmp125 * covariance(3, 6) +
                         _tmp127 * covariance(3, 5) + _tmp129 * covariance(3, 4) - _tmp188 * _tmp75;
  const Scalar _tmp195 = _tmp157 * _tmp188 + _tmp159 * _tmp191 + _tmp160 * _tmp189 +
                         _tmp161 * covariance(3, 6) + _tmp163 * covariance(3, 5) +
                         _tmp164 * covariance(3, 4);
  const Scalar _tmp196 = _tmp111 * _tmp188 + _tmp112 * _tmp190 + _tmp115 * _tmp191 +
                         _tmp116 * covariance(3, 6) + _tmp118 * covariance(3, 5) +
                         _tmp119 * covariance(3, 4);
  const Scalar _tmp197 = _tmp146 * _tmp188 + _tmp148 * _tmp191 + _tmp149 * _tmp189 +
                         _tmp151 * covariance(3, 6) + _tmp153 * covariance(3, 5) +
                         _tmp155 * covariance(3, 4);
  const Scalar _tmp198 = _tmp0 * _tmp192 + _tmp107 * _tmp196 + _tmp131 * _tmp194 +
                         _tmp142 * _tmp193 + _tmp143 * _tmp197 + _tmp166 * _tmp195 + state(3, 0);
  const Scalar _tmp199 =
      std::pow(Scalar(std::pow(_tmp167, Scalar(2)) + std::pow(_tmp177, Scalar(2)) +
                      std::pow(_tmp187, Scalar(2)) + std::pow(_tmp198, Scalar(2))),
               Scalar(Scalar(-1) / Scalar(2)));
  const Scalar _tmp200 = _tmp77 * _tmp85;
  const Scalar _tmp201 = _tmp15 * covariance(4, 5);
  const Scalar _tmp202 = _tmp133 * _tmp3 - _tmp134 * _tmp42 + _tmp136 * covariance(4, 6) +
                         _tmp137 * _tmp201 + _tmp140 * covariance(4, 4) + _tmp200;
  const Scalar _tmp203 = _tmp146 * _tmp200 + _tmp148 * _tmp3 + _tmp149 * _tmp42 +
                         _tmp151 * covariance(4, 6) + _tmp152 * _tmp201 +
                         _tmp155 * covariance(4, 4);
  const Scalar _tmp204 = _tmp157 * _tmp200 + _tmp159 * _tmp3 + _tmp160 * _tmp42 +
                         _tmp161 * covariance(4, 6) + _tmp162 * _tmp201 +
                         _tmp164 * covariance(4, 4);
  const Scalar _tmp205 = _tmp111 * _tmp200 + _tmp113 * _tmp42 + _tmp115 * _tmp3 +
                         _tmp116 * covariance(4, 6) + _tmp117 * _tmp201 +
                         _tmp119 * covariance(4, 4);
  const Scalar _tmp206 = _tmp122 * _tmp42 + _tmp124 * _tmp3 + _tmp125 * covariance(4, 6) +
                         _tmp127 * covariance(4, 5) + _tmp129 * covariance(4, 4) - _tmp200 * _tmp75;
  const Scalar _tmp207 = _tmp102 * covariance(4, 4) + _tmp200 * _tmp76 + _tmp201 * _tmp96 +
                         _tmp3 * _tmp90 + _tmp42 * _tmp92 + _tmp94 * covariance(4, 6);
  const Scalar _tmp208 = _tmp79 * _tmp85;
  const Scalar _tmp209 = _tmp5 * covariance(5, 4);
  const Scalar _tmp210 = _tmp101 * _tmp209 + _tmp208 * _tmp76 + _tmp45 * _tmp92 + _tmp7 * _tmp90 +
                         _tmp94 * covariance(5, 6) + _tmp98 * covariance(5, 5);
  const Scalar _tmp211 = _tmp25 * _tmp7;
  const Scalar _tmp212 = _tmp122 * _tmp45 + _tmp123 * _tmp211 + _tmp125 * covariance(5, 6) +
                         _tmp127 * covariance(5, 5) + _tmp128 * _tmp209 - _tmp208 * _tmp75;
  const Scalar _tmp213 = _tmp146 * _tmp208 + _tmp148 * _tmp7 + _tmp149 * _tmp45 +
                         _tmp151 * covariance(5, 6) + _tmp153 * covariance(5, 5) +
                         _tmp154 * _tmp209;
  const Scalar _tmp214 = _tmp111 * _tmp208 + _tmp113 * _tmp45 + _tmp114 * _tmp211 +
                         _tmp116 * covariance(5, 6) + _tmp118 * covariance(5, 5) +
                         _tmp119 * covariance(5, 4);
  const Scalar _tmp215 = _tmp132 * _tmp211 - _tmp134 * _tmp45 + _tmp136 * covariance(5, 6) +
                         _tmp138 * covariance(5, 5) + _tmp139 * _tmp209 + _tmp208;
  const Scalar _tmp216 = _tmp157 * _tmp208 + _tmp159 * _tmp7 + _tmp160 * _tmp45 +
                         _tmp161 * covariance(5, 6) + _tmp163 * covariance(5, 5) +
                         _tmp164 * covariance(5, 4);
  const Scalar _tmp217 = _tmp15 * covariance(6, 5);
  const Scalar _tmp218 = _tmp81 * _tmp85;
  const Scalar _tmp219 = _tmp146 * _tmp218 + _tmp148 * _tmp19 + _tmp149 * _tmp55 +
                         _tmp151 * covariance(6, 6) + _tmp152 * _tmp217 +
                         _tmp155 * covariance(6, 4);
  const Scalar _tmp220 = _tmp133 * _tmp19 - _tmp134 * _tmp55 + _tmp136 * covariance(6, 6) +
                         _tmp137 * _tmp217 + _tmp140 * covariance(6, 4) + _tmp218;
  const Scalar _tmp221 = _tmp122 * _tmp55 + _tmp124 * _tmp19 + _tmp125 * covariance(6, 6) +
                         _tmp127 * covariance(6, 5) + _tmp129 * covariance(6, 4) - _tmp218 * _tmp75;
  const Scalar _tmp222 = _tmp111 * _tmp218 + _tmp113 * _tmp55 + _tmp115 * _tmp19 +
                         _tmp116 * covariance(6, 6) + _tmp117 * _tmp217 +
                         _tmp119 * covariance(6, 4);
  const Scalar _tmp223 = _tmp157 * _tmp218 + _tmp159 * _tmp19 + _tmp160 * _tmp55 +
                         _tmp161 * covariance(6, 6) + _tmp162 * _tmp217 +
                         _tmp164 * covariance(6, 4);
  const Scalar _tmp224 = _tmp102 * covariance(6, 4) + _tmp19 * _tmp90 + _tmp217 * _tmp96 +
                         _tmp218 * _tmp76 + _tmp55 * _tmp92 + _tmp94 * covariance(6, 6);
  const Scalar _tmp225 = _tmp106 * measurement_noise(2, 1) + _tmp120 * measurement_noise(0, 1) +
                         _tmp130 * measurement_noise(4, 1) + _tmp141 * measurement_noise(5, 1) +
                         _tmp156 * measurement_noise(1, 1) + _tmp165 * measurement_noise(3, 1);
  const Scalar _tmp226 = _tmp130 * _tmp26 + _tmp141 * _tmp27;
  const Scalar _tmp227 = -_tmp130 * _tmp27 + _tmp141 * _tmp26 + 1;
  const Scalar _tmp228 = -_tmp1 * _tmp165 + _tmp130 * _tmp28 - _tmp141 * _tmp29;
  const Scalar _tmp229 = _tmp130 * _tmp29 + _tmp141 * _tmp28 - _tmp165 * _tmp2;
  const Scalar _tmp230 = -_tmp106 * covariance(6, 0) - _tmp120 * covariance(4, 0) -
                         _tmp156 * covariance(5, 0) - _tmp226 * covariance(1, 0) +
                         _tmp227 * covariance(0, 0) - _tmp228 * covariance(2, 0) -
                         _tmp229 * covariance(3, 0);
  const Scalar _tmp231 = -_tmp106 * covariance(6, 1) - _tmp120 * covariance(4, 1) -
                         _tmp156 * covariance(5, 1) - _tmp226 * covariance(1, 1) +
                         _tmp227 * covariance(0, 1) - _tmp228 * covariance(2, 1) -
                         _tmp229 * covariance(3, 1);
  const Scalar _tmp232 = _tmp106 * measurement_noise(2, 4) + _tmp120 * measurement_noise(0, 4) +
                         _tmp130 * measurement_noise(4, 4) + _tmp141 * measurement_noise(5, 4) +
                         _tmp156 * measurement_noise(1, 4) + _tmp165 * measurement_noise(3, 4);
  const Scalar _tmp233 = _tmp106 * measurement_noise(2, 0) + _tmp120 * measurement_noise(0, 0) +
                         _tmp130 * measurement_noise(4, 0) + _tmp141 * measurement_noise(5, 0) +
                         _tmp156 * measurement_noise(1, 0) + _tmp165 * measurement_noise(3, 0);
  const Scalar _tmp234 = -_tmp106 * covariance(6, 6) - _tmp120 * covariance(4, 6) -
                         _tmp156 * covariance(5, 6) - _tmp226 * covariance(1, 6) +
                         _tmp227 * covariance(0, 6) - _tmp228 * covariance(2, 6) -
                         _tmp229 * covariance(3, 6);
  const Scalar _tmp235 = -_tmp106 * covariance(6, 3) - _tmp120 * covariance(4, 3) -
                         _tmp156 * covariance(5, 3) - _tmp226 * covariance(1, 3) +
                         _tmp227 * covariance(0, 3) - _tmp228 * covariance(2, 3) -
                         _tmp229 * covariance(3, 3);
  const Scalar _tmp236 = _tmp106 * measurement_noise(2, 3) + _tmp120 * measurement_noise(0, 3) +
                         _tmp130 * measurement_noise(4, 3) + _tmp141 * measurement_noise(5, 3) +
                         _tmp156 * measurement_noise(1, 3) + _tmp165 * measurement_noise(3, 3);
  const Scalar _tmp237 = _tmp106 * measurement_noise(2, 2) + _tmp120 * measurement_noise(0, 2) +
                         _tmp130 * measurement_noise(4, 2) + _tmp141 * measurement_noise(5, 2) +
                         _tmp156 * measurement_noise(1, 2) + _tmp165 * measurement_noise(3, 2);
  const Scalar _tmp238 = -_tmp106 * covariance(6, 5) - _tmp120 * covariance(4, 5) -
                         _tmp156 * covariance(5, 5) - _tmp226 * covariance(1, 5) +
                         _tmp227 * covariance(0, 5) - _tmp228 * covariance(2, 5) -
                         _tmp229 * covariance(3, 5);
  const Scalar _tmp239 = _tmp106 * measurement_noise(2, 5) + _tmp120 * measurement_noise(0, 5) +
                         _tmp130 * measurement_noise(4, 5) + _tmp141 * measurement_noise(5, 5) +
                         _tmp156 * measurement_noise(1, 5) + _tmp165 * measurement_noise(3, 5);
  const Scalar _tmp240 = -_tmp106 * covariance(6, 4) - _tmp120 * covariance(4, 4) -
                         _tmp156 * covariance(5, 4) - _tmp226 * covariance(1, 4) +
                         _tmp227 * covariance(0, 4) - _tmp228 * covariance(2, 4) -
                         _tmp229 * covariance(3, 4);
  const Scalar _tmp241 = -_tmp106 * covariance(6, 2) - _tmp120 * covariance(4, 2) -
                         _tmp156 * covariance(5, 2) - _tmp226 * covariance(1, 2) +
                         _tmp227 * covariance(0, 2) - _tmp228 * covariance(2, 2) -
                         _tmp229 * covariance(3, 2);
  const Scalar _tmp242 = _tmp171 * measurement_noise(4, 0) + _tmp172 * measurement_noise(1, 0) +
                         _tmp173 * measurement_noise(5, 0) + _tmp174 * measurement_noise(2, 0) +
                         _tmp175 * measurement_noise(3, 0) + _tmp176 * measurement_noise(0, 0);
  const Scalar _tmp243 = -_tmp171 * _tmp26 - _tmp173 * _tmp27 + 1;
  const Scalar _tmp244 = _tmp171 * _tmp27 - _tmp173 * _tmp26;
  const Scalar _tmp245 = -_tmp1 * _tmp175 + _tmp171 * _tmp28 - _tmp173 * _tmp29;
  const Scalar _tmp246 = _tmp171 * _tmp29 + _tmp173 * _tmp28 - _tmp175 * _tmp2;
  const Scalar _tmp247 = -_tmp172 * covariance(5, 6) - _tmp174 * covariance(6, 6) -
                         _tmp176 * covariance(4, 6) + _tmp243 * covariance(1, 6) -
                         _tmp244 * covariance(0, 6) - _tmp245 * covariance(2, 6) -
                         _tmp246 * covariance(3, 6);
  const Scalar _tmp248 = _tmp171 * measurement_noise(4, 2) + _tmp172 * measurement_noise(1, 2) +
                         _tmp173 * measurement_noise(5, 2) + _tmp174 * measurement_noise(2, 2) +
                         _tmp175 * measurement_noise(3, 2) + _tmp176 * measurement_noise(0, 2);
  const Scalar _tmp249 = -_tmp172 * covariance(5, 2) - _tmp174 * covariance(6, 2) -
                         _tmp176 * covariance(4, 2) + _tmp243 * covariance(1, 2) -
                         _tmp244 * covariance(0, 2) - _tmp245 * covariance(2, 2) -
                         _tmp246 * covariance(3, 2);
  const Scalar _tmp250 = -_tmp172 * covariance(5, 3) - _tmp174 * covariance(6, 3) -
                         _tmp176 * covariance(4, 3) + _tmp243 * covariance(1, 3) -
                         _tmp244 * covariance(0, 3) - _tmp245 * covariance(2, 3) -
                         _tmp246 * covariance(3, 3);
  const Scalar _tmp251 = _tmp171 * measurement_noise(4, 5) + _tmp172 * measurement_noise(1, 5) +
                         _tmp173 * measurement_noise(5, 5) + _tmp174 * measurement_noise(2, 5) +
                         _tmp175 * measurement_noise(3, 5) + _tmp176 * measurement_noise(0, 5);
  const Scalar _tmp252 = -_tmp172 * covariance(5, 0) - _tmp174 * covariance(6, 0) -
                         _tmp176 * covariance(4, 0) + _tmp243 * covariance(1, 0) -
                         _tmp244 * covariance(0, 0) - _tmp245 * covariance(2, 0) -
                         _tmp246 * covariance(3, 0);
  const Scalar _tmp253 = _tmp171 * measurement_noise(4, 1) + _tmp172 * measurement_noise(1, 1) +
                         _tmp173 * measurement_noise(5, 1) + _tmp174 * measurement_noise(2, 1) +
                         _tmp175 * measurement_noise(3, 1) + _tmp176 * measurement_noise(0, 1);
  const Scalar _tmp254 = -_tmp172 * covariance(5, 4) - _tmp174 * covariance(6, 4) -
                         _tmp176 * covariance(4, 4) + _tmp243 * covariance(1, 4) -
                         _tmp244 * covariance(0, 4) - _tmp245 * covariance(2, 4) -
                         _tmp246 * covariance(3, 4);
  const Scalar _tmp255 = -_tmp172 * covariance(5, 1) - _tmp174 * covariance(6, 1) -
                         _tmp176 * covariance(4, 1) + _tmp243 * covariance(1, 1) -
                         _tmp244 * covariance(0, 1) - _tmp245 * covariance(2, 1) -
                         _tmp246 * covariance(3, 1);
  const Scalar _tmp256 = _tmp171 * measurement_noise(4, 4) + _tmp172 * measurement_noise(1, 4) +
                         _tmp173 * measurement_noise(5, 4) + _tmp174 * measurement_noise(2, 4) +
                         _tmp175 * measurement_noise(3, 4) + _tmp176 * measurement_noise(0, 4);
  const Scalar _tmp257 = -_tmp172 * covariance(5, 5) - _tmp174 * covariance(6, 5) -
                         _tmp176 * covariance(4, 5) + _tmp243 * covariance(1, 5) -
                         _tmp244 * covariance(0, 5) - _tmp245 * covariance(2, 5) -
                         _tmp246 * covariance(3, 5);
  const Scalar _tmp258 = _tmp171 * measurement_noise(4, 3) + _tmp172 * measurement_noise(1, 3) +
                         _tmp173 * measurement_noise(5, 3) + _tmp174 * measurement_noise(2, 3) +
                         _tmp175 * measurement_noise(3, 3) + _tmp176 * measurement_noise(0, 3);
  const Scalar _tmp259 = _tmp181 * measurement_noise(4, 1) + _tmp182 * measurement_noise(0, 1) +
                         _tmp183 * measurement_noise(2, 1) + _tmp184 * measurement_noise(3, 1) +
                         _tmp185 * measurement_noise(1, 1) + _tmp186 * measurement_noise(5, 1);
  const Scalar _tmp260 = _tmp181 * measurement_noise(4, 5) + _tmp182 * measurement_noise(0, 5) +
                         _tmp183 * measurement_noise(2, 5) + _tmp184 * measurement_noise(3, 5) +
                         _tmp185 * measurement_noise(1, 5) + _tmp186 * measurement_noise(5, 5);
  const Scalar _tmp261 = _tmp181 * _tmp27 - _tmp186 * _tmp26;
  const Scalar _tmp262 = _tmp181 * _tmp26 + _tmp186 * _tmp27;
  const Scalar _tmp263 = _tmp181 * _tmp29 - _tmp184 * _tmp2 + _tmp186 * _tmp28;
  const Scalar _tmp264 = _tmp1 * _tmp184 - _tmp181 * _tmp28 + _tmp186 * _tmp29 + 1;
  const Scalar _tmp265 = -_tmp182 * covariance(4, 4) - _tmp183 * covariance(6, 4) -
                         _tmp185 * covariance(5, 4) - _tmp261 * covariance(0, 4) -
                         _tmp262 * covariance(1, 4) - _tmp263 * covariance(3, 4) +
                         _tmp264 * covariance(2, 4);
  const Scalar _tmp266 = -_tmp182 * covariance(4, 5) - _tmp183 * covariance(6, 5) -
                         _tmp185 * covariance(5, 5) - _tmp261 * covariance(0, 5) -
                         _tmp262 * covariance(1, 5) - _tmp263 * covariance(3, 5) +
                         _tmp264 * covariance(2, 5);
  const Scalar _tmp267 = _tmp181 * measurement_noise(4, 2) + _tmp182 * measurement_noise(0, 2) +
                         _tmp183 * measurement_noise(2, 2) + _tmp184 * measurement_noise(3, 2) +
                         _tmp185 * measurement_noise(1, 2) + _tmp186 * measurement_noise(5, 2);
  const Scalar _tmp268 = _tmp181 * measurement_noise(4, 3) + _tmp182 * measurement_noise(0, 3) +
                         _tmp183 * measurement_noise(2, 3) + _tmp184 * measurement_noise(3, 3) +
                         _tmp185 * measurement_noise(1, 3) + _tmp186 * measurement_noise(5, 3);
  const Scalar _tmp269 = -_tmp182 * covariance(4, 0) - _tmp183 * covariance(6, 0) -
                         _tmp185 * covariance(5, 0) - _tmp261 * covariance(0, 0) -
                         _tmp262 * covariance(1, 0) - _tmp263 * covariance(3, 0) +
                         _tmp264 * covariance(2, 0);
  const Scalar _tmp270 = -_tmp182 * covariance(4, 2) - _tmp183 * covariance(6, 2) -
                         _tmp185 * covariance(5, 2) - _tmp261 * covariance(0, 2) -
                         _tmp262 * covariance(1, 2) - _tmp263 * covariance(3, 2) +
                         _tmp264 * covariance(2, 2);
  const Scalar _tmp271 = -_tmp182 * covariance(4, 3) - _tmp183 * covariance(6, 3) -
                         _tmp185 * covariance(5, 3) - _tmp261 * covariance(0, 3) -
                         _tmp262 * covariance(1, 3) - _tmp263 * covariance(3, 3) +
                         _tmp264 * covariance(2, 3);
  const Scalar _tmp272 = _tmp181 * measurement_noise(4, 0) + _tmp182 * measurement_noise(0, 0) +
                         _tmp183 * measurement_noise(2, 0) + _tmp184 * measurement_noise(3, 0) +
                         _tmp185 * measurement_noise(1, 0) + _tmp186 * measurement_noise(5, 0);
  const Scalar _tmp273 = -_tmp182 * covariance(4, 6) - _tmp183 * covariance(6, 6) -
                         _tmp185 * covariance(5, 6) - _tmp261 * covariance(0, 6) -
                         _tmp262 * covariance(1, 6) - _tmp263 * covariance(3, 6) +
                         _tmp264 * covariance(2, 6);
  const Scalar _tmp274 = -_tmp182 * covariance(4, 1) - _tmp183 * covariance(6, 1) -
                         _tmp185 * covariance(5, 1) - _tmp261 * covariance(0, 1) -
                         _tmp262 * covariance(1, 1) - _tmp263 * covariance(3, 1) +
                         _tmp264 * covariance(2, 1);
  const Scalar _tmp275 = _tmp181 * measurement_noise(4, 4) + _tmp182 * measurement_noise(0, 4) +
                         _tmp183 * measurement_noise(2, 4) + _tmp184 * measurement_noise(3, 4) +
                         _tmp185 * measurement_noise(1, 4) + _tmp186 * measurement_noise(5, 4);
  const Scalar _tmp276 = -_tmp193 * _tmp28 - _tmp194 * _tmp29 + _tmp195 * _tmp2 + 1;
  const Scalar _tmp277 = -_tmp1 * _tmp195 - _tmp193 * _tmp29 + _tmp194 * _tmp28;
  const Scalar _tmp278 = -_tmp193 * _tmp26 + _tmp194 * _tmp27;
  const Scalar _tmp279 = _tmp193 * _tmp27 + _tmp194 * _tmp26;
  const Scalar _tmp280 = -_tmp192 * covariance(6, 4) - _tmp196 * covariance(4, 4) -
                         _tmp197 * covariance(5, 4) + _tmp276 * covariance(3, 4) -
                         _tmp277 * covariance(2, 4) - _tmp278 * covariance(0, 4) -
                         _tmp279 * covariance(1, 4);
  const Scalar _tmp281 = -_tmp192 * covariance(6, 6) - _tmp196 * covariance(4, 6) -
                         _tmp197 * covariance(5, 6) + _tmp276 * covariance(3, 6) -
                         _tmp277 * covariance(2, 6) - _tmp278 * covariance(0, 6) -
                         _tmp279 * covariance(1, 6);
  const Scalar _tmp282 = _tmp192 * measurement_noise(2, 2) + _tmp193 * measurement_noise(5, 2) +
                         _tmp194 * measurement_noise(4, 2) + _tmp195 * measurement_noise(3, 2) +
                         _tmp196 * measurement_noise(0, 2) + _tmp197 * measurement_noise(1, 2);
  const Scalar _tmp283 = -_tmp192 * covariance(6, 1) - _tmp196 * covariance(4, 1) -
                         _tmp197 * covariance(5, 1) + _tmp276 * covariance(3, 1) -
                         _tmp277 * covariance(2, 1) - _tmp278 * covariance(0, 1) -
                         _tmp279 * covariance(1, 1);
  const Scalar _tmp284 = -_tmp192 * covariance(6, 0) - _tmp196 * covariance(4, 0) -
                         _tmp197 * covariance(5, 0) + _tmp276 * covariance(3, 0) -
                         _tmp277 * covariance(2, 0) - _tmp278 * covariance(0, 0) -
                         _tmp279 * covariance(1, 0);
  const Scalar _tmp285 = _tmp192 * measurement_noise(2, 3) + _tmp193 * measurement_noise(5, 3) +
                         _tmp194 * measurement_noise(4, 3) + _tmp195 * measurement_noise(3, 3) +
                         _tmp196 * measurement_noise(0, 3) + _tmp197 * measurement_noise(1, 3);
  const Scalar _tmp286 = -_tmp192 * covariance(6, 5) - _tmp196 * covariance(4, 5) -
                         _tmp197 * covariance(5, 5) + _tmp276 * covariance(3, 5) -
                         _tmp277 * covariance(2, 5) - _tmp278 * covariance(0, 5) -
                         _tmp279 * covariance(1, 5);
  const Scalar _tmp287 = _tmp192 * measurement_noise(2, 5) + _tmp193 * measurement_noise(5, 5) +
                         _tmp194 * measurement_noise(4, 5) + _tmp195 * measurement_noise(3, 5) +
                         _tmp196 * measurement_noise(0, 5) + _tmp197 * measurement_noise(1, 5);
  const Scalar _tmp288 = _tmp192 * measurement_noise(2, 1) + _tmp193 * measurement_noise(5, 1) +
                         _tmp194 * measurement_noise(4, 1) + _tmp195 * measurement_noise(3, 1) +
                         _tmp196 * measurement_noise(0, 1) + _tmp197 * measurement_noise(1, 1);
  const Scalar _tmp289 = _tmp192 * measurement_noise(2, 0) + _tmp193 * measurement_noise(5, 0) +
                         _tmp194 * measurement_noise(4, 0) + _tmp195 * measurement_noise(3, 0) +
                         _tmp196 * measurement_noise(0, 0) + _tmp197 * measurement_noise(1, 0);
  const Scalar _tmp290 = -_tmp192 * covariance(6, 2) - _tmp196 * covariance(4, 2) -
                         _tmp197 * covariance(5, 2) + _tmp276 * covariance(3, 2) -
                         _tmp277 * covariance(2, 2) - _tmp278 * covariance(0, 2) -
                         _tmp279 * covariance(1, 2);
  const Scalar _tmp291 = -_tmp192 * covariance(6, 3) - _tmp196 * covariance(4, 3) -
                         _tmp197 * covariance(5, 3) + _tmp276 * covariance(3, 3) -
                         _tmp277 * covariance(2, 3) - _tmp278 * covariance(0, 3) -
                         _tmp279 * covariance(1, 3);
  const Scalar _tmp292 = _tmp192 * measurement_noise(2, 4) + _tmp193 * measurement_noise(5, 4) +
                         _tmp194 * measurement_noise(4, 4) + _tmp195 * measurement_noise(3, 4) +
                         _tmp196 * measurement_noise(0, 4) + _tmp197 * measurement_noise(1, 4);
  const Scalar _tmp293 = 2 * _tmp206;
  const Scalar _tmp294 = _tmp202 * _tmp27 + _tmp293 * state(2, 0);
  const Scalar _tmp295 = -_tmp202 * _tmp26 + _tmp293 * state(3, 0);
  const Scalar _tmp296 = -_tmp1 * _tmp204 - _tmp202 * _tmp29 + _tmp293 * state(1, 0);
  const Scalar _tmp297 = -_tmp2 * _tmp204 + _tmp202 * _tmp28 + _tmp293 * state(0, 0);
  const Scalar _tmp298 = 1 - _tmp205;
  const Scalar _tmp299 = -_tmp203 * covariance(5, 4) - _tmp207 * covariance(6, 4) -
                         _tmp294 * covariance(1, 4) - _tmp295 * covariance(0, 4) -
                         _tmp296 * covariance(2, 4) - _tmp297 * covariance(3, 4) +
                         _tmp298 * covariance(4, 4);
  const Scalar _tmp300 = -_tmp203 * covariance(5, 0) - _tmp207 * covariance(6, 0) -
                         _tmp294 * covariance(1, 0) - _tmp295 * covariance(0, 0) -
                         _tmp296 * covariance(2, 0) - _tmp297 * covariance(3, 0) +
                         _tmp298 * covariance(4, 0);
  const Scalar _tmp301 = _tmp202 * measurement_noise(5, 3) + _tmp203 * measurement_noise(1, 3) +
                         _tmp204 * measurement_noise(3, 3) + _tmp205 * measurement_noise(0, 3) +
                         _tmp206 * measurement_noise(4, 3) + _tmp207 * measurement_noise(2, 3);
  const Scalar _tmp302 = _tmp202 * measurement_noise(5, 4) + _tmp203 * measurement_noise(1, 4) +
                         _tmp204 * measurement_noise(3, 4) + _tmp205 * measurement_noise(0, 4) +
                         _tmp206 * measurement_noise(4, 4) + _tmp207 * measurement_noise(2, 4);
  const Scalar _tmp303 = -_tmp203 * covariance(5, 6) - _tmp207 * covariance(6, 6) -
                         _tmp294 * covariance(1, 6) - _tmp295 * covariance(0, 6) -
                         _tmp296 * covariance(2, 6) - _tmp297 * covariance(3, 6) +
                         _tmp298 * covariance(4, 6);
  const Scalar _tmp304 = _tmp202 * measurement_noise(5, 2) + _tmp203 * measurement_noise(1, 2) +
                         _tmp204 * measurement_noise(3, 2) + _tmp205 * measurement_noise(0, 2) +
                         _tmp206 * measurement_noise(4, 2) + _tmp207 * measurement_noise(2, 2);
  const Scalar _tmp305 = _tmp202 * measurement_noise(5, 0) + _tmp203 * measurement_noise(1, 0) +
                         _tmp204 * measurement_noise(3, 0) + _tmp205 * measurement_noise(0, 0) +
                         _tmp206 * measurement_noise(4, 0) + _tmp207 * measurement_noise(2, 0);
  const Scalar _tmp306 = -_tmp203 * covariance(5, 3) - _tmp207 * covariance(6, 3) -
                         _tmp294 * covariance(1, 3) - _tmp295 * covariance(0, 3) -
                         _tmp296 * covariance(2, 3) - _tmp297 * covariance(3, 3) +
                         _tmp298 * covariance(4, 3);
  const Scalar _tmp307 = -_tmp203 * covariance(5, 2) - _tmp207 * covariance(6, 2) -
                         _tmp294 * covariance(1, 2) - _tmp295 * covariance(0, 2) -
                         _tmp296 * covariance(2, 2) - _tmp297 * covariance(3, 2) +
                         _tmp298 * covariance(4, 2);
  const Scalar _tmp308 = -_tmp203 * covariance(5, 5) - _tmp207 * covariance(6, 5) -
                         _tmp294 * covariance(1, 5) - _tmp295 * covariance(0, 5) -
                         _tmp296 * covariance(2, 5) - _tmp297 * covariance(3, 5) +
                         _tmp298 * covariance(4, 5);
  const Scalar _tmp309 = -_tmp203 * covariance(5, 1) - _tmp207 * covariance(6, 1) -
                         _tmp294 * covariance(1, 1) - _tmp295 * covariance(0, 1) -
                         _tmp296 * covariance(2, 1) - _tmp297 * covariance(3, 1) +
                         _tmp298 * covariance(4, 1);
  const Scalar _tmp310 = _tmp202 * measurement_noise(5, 1) + _tmp203 * measurement_noise(1, 1) +
                         _tmp204 * measurement_noise(3, 1) + _tmp205 * measurement_noise(0, 1) +
                         _tmp206 * measurement_noise(4, 1) + _tmp207 * measurement_noise(2, 1);
  const Scalar _tmp311 = _tmp202 * measurement_noise(5, 5) + _tmp203 * measurement_noise(1, 5) +
                         _tmp204 * measurement_noise(3, 5) + _tmp205 * measurement_noise(0, 5) +
                         _tmp206 * measurement_noise(4, 5) + _tmp207 * measurement_noise(2, 5);
  const Scalar _tmp312 = -_tmp2 * _tmp216 + _tmp212 * _tmp29 + _tmp215 * _tmp28;
  const Scalar _tmp313 = -_tmp1 * _tmp216 + _tmp212 * _tmp28 - _tmp215 * _tmp29;
  const Scalar _tmp314 = 1 - _tmp213;
  const Scalar _tmp315 = _tmp212 * _tmp27 - _tmp215 * _tmp26;
  const Scalar _tmp316 = _tmp212 * _tmp26 + _tmp215 * _tmp27;
  const Scalar _tmp317 = -_tmp210 * covariance(6, 6) - _tmp214 * covariance(4, 6) -
                         _tmp312 * covariance(3, 6) - _tmp313 * covariance(2, 6) +
                         _tmp314 * covariance(5, 6) - _tmp315 * covariance(0, 6) -
                         _tmp316 * covariance(1, 6);
  const Scalar _tmp318 = _tmp210 * measurement_noise(2, 5) + _tmp212 * measurement_noise(4, 5) +
                         _tmp213 * measurement_noise(1, 5) + _tmp214 * measurement_noise(0, 5) +
                         _tmp215 * measurement_noise(5, 5) + _tmp216 * measurement_noise(3, 5);
  const Scalar _tmp319 = -_tmp210 * covariance(6, 1) - _tmp214 * covariance(4, 1) -
                         _tmp312 * covariance(3, 1) - _tmp313 * covariance(2, 1) +
                         _tmp314 * covariance(5, 1) - _tmp315 * covariance(0, 1) -
                         _tmp316 * covariance(1, 1);
  const Scalar _tmp320 = _tmp210 * measurement_noise(2, 2) + _tmp212 * measurement_noise(4, 2) +
                         _tmp213 * measurement_noise(1, 2) + _tmp214 * measurement_noise(0, 2) +
                         _tmp215 * measurement_noise(5, 2) + _tmp216 * measurement_noise(3, 2);
  const Scalar _tmp321 = _tmp210 * measurement_noise(2, 1) + _tmp212 * measurement_noise(4, 1) +
                         _tmp213 * measurement_noise(1, 1) + _tmp214 * measurement_noise(0, 1) +
                         _tmp215 * measurement_noise(5, 1) + _tmp216 * measurement_noise(3, 1);
  const Scalar _tmp322 = -_tmp210 * covariance(6, 0) - _tmp214 * covariance(4, 0) -
                         _tmp312 * covariance(3, 0) - _tmp313 * covariance(2, 0) +
                         _tmp314 * covariance(5, 0) - _tmp315 * covariance(0, 0) -
                         _tmp316 * covariance(1, 0);
  const Scalar _tmp323 = -_tmp210 * covariance(6, 2) - _tmp214 * covariance(4, 2) -
                         _tmp312 * covariance(3, 2) - _tmp313 * covariance(2, 2) +
                         _tmp314 * covariance(5, 2) - _tmp315 * covariance(0, 2) -
                         _tmp316 * covariance(1, 2);
  const Scalar _tmp324 = -_tmp210 * covariance(6, 3) - _tmp214 * covariance(4, 3) -
                         _tmp312 * covariance(3, 3) - _tmp313 * covariance(2, 3) +
                         _tmp314 * covariance(5, 3) - _tmp315 * covariance(0, 3) -
                         _tmp316 * covariance(1, 3);
  const Scalar _tmp325 = _tmp210 * measurement_noise(2, 0) + _tmp212 * measurement_noise(4, 0) +
                         _tmp213 * measurement_noise(1, 0) + _tmp214 * measurement_noise(0, 0) +
                         _tmp215 * measurement_noise(5, 0) + _tmp216 * measurement_noise(3, 0);
  const Scalar _tmp326 = -_tmp210 * covariance(6, 5) - _tmp214 * covariance(4, 5) -
                         _tmp312 * covariance(3, 5) - _tmp313 * covariance(2, 5) +
                         _tmp314 * covariance(5, 5) - _tmp315 * covariance(0, 5) -
                         _tmp316 * covariance(1, 5);
  const Scalar _tmp327 = _tmp210 * measurement_noise(2, 3) + _tmp212 * measurement_noise(4, 3) +
                         _tmp213 * measurement_noise(1, 3) + _tmp214 * measurement_noise(0, 3) +
                         _tmp215 * measurement_noise(5, 3) + _tmp216 * measurement_noise(3, 3);
  const Scalar _tmp328 = _tmp210 * measurement_noise(2, 4) + _tmp212 * measurement_noise(4, 4) +
                         _tmp213 * measurement_noise(1, 4) + _tmp214 * measurement_noise(0, 4) +
                         _tmp215 * measurement_noise(5, 4) + _tmp216 * measurement_noise(3, 4);
  const Scalar _tmp329 = -_tmp210 * covariance(6, 4) - _tmp214 * covariance(4, 4) -
                         _tmp312 * covariance(3, 4) - _tmp313 * covariance(2, 4) +
                         _tmp314 * covariance(5, 4) - _tmp315 * covariance(0, 4) -
                         _tmp316 * covariance(1, 4);
  const Scalar _tmp330 = _tmp219 * measurement_noise(1, 1) + _tmp220 * measurement_noise(5, 1) +
                         _tmp221 * measurement_noise(4, 1) + _tmp222 * measurement_noise(0, 1) +
                         _tmp223 * measurement_noise(3, 1) + _tmp224 * measurement_noise(2, 1);
  const Scalar _tmp331 = _tmp219 * measurement_noise(1, 0) + _tmp220 * measurement_noise(5, 0) +
                         _tmp221 * measurement_noise(4, 0) + _tmp222 * measurement_noise(0, 0) +
                         _tmp223 * measurement_noise(3, 0) + _tmp224 * measurement_noise(2, 0);
  const Scalar _tmp332 = 2 * _tmp221;
  const Scalar _tmp333 = -_tmp1 * _tmp223 - _tmp220 * _tmp29 + _tmp332 * state(1, 0);
  const Scalar _tmp334 = -_tmp2 * _tmp223 + _tmp220 * _tmp28 + _tmp332 * state(0, 0);
  const Scalar _tmp335 = _tmp220 * _tmp27 + _tmp332 * state(2, 0);
  const Scalar _tmp336 = -_tmp220 * _tmp26 + _tmp332 * state(3, 0);
  const Scalar _tmp337 = 1 - _tmp224;
  const Scalar _tmp338 = -_tmp219 * covariance(5, 1) - _tmp222 * covariance(4, 1) -
                         _tmp333 * covariance(2, 1) - _tmp334 * covariance(3, 1) -
                         _tmp335 * covariance(1, 1) - _tmp336 * covariance(0, 1) +
                         _tmp337 * covariance(6, 1);
  const Scalar _tmp339 = -_tmp219 * covariance(5, 6) - _tmp222 * covariance(4, 6) -
                         _tmp333 * covariance(2, 6) - _tmp334 * covariance(3, 6) -
                         _tmp335 * covariance(1, 6) - _tmp336 * covariance(0, 6) +
                         _tmp337 * covariance(6, 6);
  const Scalar _tmp340 = -_tmp219 * covariance(5, 2) - _tmp222 * covariance(4, 2) -
                         _tmp333 * covariance(2, 2) - _tmp334 * covariance(3, 2) -
                         _tmp335 * covariance(1, 2) - _tmp336 * covariance(0, 2) +
                         _tmp337 * covariance(6, 2);
  const Scalar _tmp341 = -_tmp219 * covariance(5, 3) - _tmp222 * covariance(4, 3) -
                         _tmp333 * covariance(2, 3) - _tmp334 * covariance(3, 3) -
                         _tmp335 * covariance(1, 3) - _tmp336 * covariance(0, 3) +
                         _tmp337 * covariance(6, 3);
  const Scalar _tmp342 = _tmp219 * measurement_noise(1, 4) + _tmp220 * measurement_noise(5, 4) +
                         _tmp221 * measurement_noise(4, 4) + _tmp222 * measurement_noise(0, 4) +
                         _tmp223 * measurement_noise(3, 4) + _tmp224 * measurement_noise(2, 4);
  const Scalar _tmp343 = -_tmp219 * covariance(5, 0) - _tmp222 * covariance(4, 0) -
                         _tmp333 * covariance(2, 0) - _tmp334 * covariance(3, 0) -
                         _tmp335 * covariance(1, 0) - _tmp336 * covariance(0, 0) +
                         _tmp337 * covariance(6, 0);
  const Scalar _tmp344 = _tmp219 * measurement_noise(1, 2) + _tmp220 * measurement_noise(5, 2) +
                         _tmp221 * measurement_noise(4, 2) + _tmp222 * measurement_noise(0, 2) +
                         _tmp223 * measurement_noise(3, 2) + _tmp224 * measurement_noise(2, 2);
  const Scalar _tmp345 = -_tmp219 * covariance(5, 5) - _tmp222 * covariance(4, 5) -
                         _tmp333 * covariance(2, 5) - _tmp334 * covariance(3, 5) -
                         _tmp335 * covariance(1, 5) - _tmp336 * covariance(0, 5) +
                         _tmp337 * covariance(6, 5);
  const Scalar _tmp346 = -_tmp219 * covariance(5, 4) - _tmp222 * covariance(4, 4) -
                         _tmp333 * covariance(2, 4) - _tmp334 * covariance(3, 4) -
                         _tmp335 * covariance(1, 4) - _tmp336 * covariance(0, 4) +
                         _tmp337 * covariance(6, 4);
  const Scalar _tmp347 = _tmp219 * measurement_noise(1, 3) + _tmp220 * measurement_noise(5, 3) +
                         _tmp221 * measurement_noise(4, 3) + _tmp222 * measurement_noise(0, 3) +
                         _tmp223 * measurement_noise(3, 3) + _tmp224 * measurement_noise(2, 3);
  const Scalar _tmp348 = _tmp219 * measurement_noise(1, 5) + _tmp220 * measurement_noise(5, 5) +
                         _tmp221 * measurement_noise(4, 5) + _tmp222 * measurement_noise(0, 5) +
                         _tmp223 * measurement_noise(3, 5) + _tmp224 * measurement_noise(2, 5);

  // Output terms (2)
  if (new_state != nullptr) {
    Eigen::Matrix<Scalar, 7, 1>& _new_state = (*new_state);

    _new_state(0, 0) = _tmp167 * _tmp199;
    _new_state(1, 0) = _tmp177 * _tmp199;
    _new_state(2, 0) = _tmp187 * _tmp199;
    _new_state(3, 0) = _tmp198 * _tmp199;
    _new_state(4, 0) = _tmp0 * _tmp207 + _tmp107 * _tmp205 + _tmp131 * _tmp206 + _tmp142 * _tmp202 +
                       _tmp143 * _tmp203 + _tmp166 * _tmp204 + state(4, 0);
    _new_state(5, 0) = _tmp0 * _tmp210 + _tmp107 * _tmp214 + _tmp131 * _tmp212 + _tmp142 * _tmp215 +
                       _tmp143 * _tmp213 + _tmp166 * _tmp216 + state(5, 0);
    _new_state(6, 0) = _tmp0 * _tmp224 + _tmp107 * _tmp222 + _tmp131 * _tmp221 + _tmp142 * _tmp220 +
                       _tmp143 * _tmp219 + _tmp166 * _tmp223 + state(6, 0);
  }

  if (new_covariance != nullptr) {
    Eigen::Matrix<Scalar, 7, 7>& _new_covariance = (*new_covariance);

    _new_covariance(0, 0) = -_tmp106 * _tmp234 + _tmp106 * _tmp237 + _tmp120 * _tmp233 -
                            _tmp120 * _tmp240 + _tmp130 * _tmp232 + _tmp141 * _tmp239 +
                            _tmp156 * _tmp225 - _tmp156 * _tmp238 + _tmp165 * _tmp236 -
                            _tmp226 * _tmp231 + _tmp227 * _tmp230 - _tmp228 * _tmp241 -
                            _tmp229 * _tmp235;
    _new_covariance(1, 0) = -_tmp106 * _tmp247 + _tmp106 * _tmp248 + _tmp120 * _tmp242 -
                            _tmp120 * _tmp254 + _tmp130 * _tmp256 + _tmp141 * _tmp251 +
                            _tmp156 * _tmp253 - _tmp156 * _tmp257 + _tmp165 * _tmp258 -
                            _tmp226 * _tmp255 + _tmp227 * _tmp252 - _tmp228 * _tmp249 -
                            _tmp229 * _tmp250;
    _new_covariance(2, 0) = _tmp106 * _tmp267 - _tmp106 * _tmp273 - _tmp120 * _tmp265 +
                            _tmp120 * _tmp272 + _tmp130 * _tmp275 + _tmp141 * _tmp260 +
                            _tmp156 * _tmp259 - _tmp156 * _tmp266 + _tmp165 * _tmp268 -
                            _tmp226 * _tmp274 + _tmp227 * _tmp269 - _tmp228 * _tmp270 -
                            _tmp229 * _tmp271;
    _new_covariance(3, 0) = -_tmp106 * _tmp281 + _tmp106 * _tmp282 - _tmp120 * _tmp280 +
                            _tmp120 * _tmp289 + _tmp130 * _tmp292 + _tmp141 * _tmp287 -
                            _tmp156 * _tmp286 + _tmp156 * _tmp288 + _tmp165 * _tmp285 -
                            _tmp226 * _tmp283 + _tmp227 * _tmp284 - _tmp228 * _tmp290 -
                            _tmp229 * _tmp291;
    _new_covariance(4, 0) = -_tmp106 * _tmp303 + _tmp106 * _tmp304 - _tmp120 * _tmp299 +
                            _tmp120 * _tmp305 + _tmp130 * _tmp302 + _tmp141 * _tmp311 -
                            _tmp156 * _tmp308 + _tmp156 * _tmp310 + _tmp165 * _tmp301 -
                            _tmp226 * _tmp309 + _tmp227 * _tmp300 - _tmp228 * _tmp307 -
                            _tmp229 * _tmp306;
    _new_covariance(5, 0) = -_tmp106 * _tmp317 + _tmp106 * _tmp320 + _tmp120 * _tmp325 -
                            _tmp120 * _tmp329 + _tmp130 * _tmp328 + _tmp141 * _tmp318 +
                            _tmp156 * _tmp321 - _tmp156 * _tmp326 + _tmp165 * _tmp327 -
                            _tmp226 * _tmp319 + _tmp227 * _tmp322 - _tmp228 * _tmp323 -
                            _tmp229 * _tmp324;
    _new_covariance(6, 0) = -_tmp106 * _tmp339 + _tmp106 * _tmp344 + _tmp120 * _tmp331 -
                            _tmp120 * _tmp346 + _tmp130 * _tmp342 + _tmp141 * _tmp348 +
                            _tmp156 * _tmp330 - _tmp156 * _tmp345 + _tmp165 * _tmp347 -
                            _tmp226 * _tmp338 + _tmp227 * _tmp343 - _tmp228 * _tmp340 -
                            _tmp229 * _tmp341;
    _new_covariance(0, 1) = _tmp171 * _tmp232 + _tmp172 * _tmp225 - _tmp172 * _tmp238 +
                            _tmp173 * _tmp239 - _tmp174 * _tmp234 + _tmp174 * _tmp237 +
                            _tmp175 * _tmp236 + _tmp176 * _tmp233 - _tmp176 * _tmp240 -
                            _tmp230 * _tmp244 + _tmp231 * _tmp243 - _tmp235 * _tmp246 -
                            _tmp241 * _tmp245;
    _new_covariance(1, 1) = _tmp171 * _tmp256 + _tmp172 * _tmp253 - _tmp172 * _tmp257 +
                            _tmp173 * _tmp251 - _tmp174 * _tmp247 + _tmp174 * _tmp248 +
                            _tmp175 * _tmp258 + _tmp176 * _tmp242 - _tmp176 * _tmp254 +
                            _tmp243 * _tmp255 - _tmp244 * _tmp252 - _tmp245 * _tmp249 -
                            _tmp246 * _tmp250;
    _new_covariance(2, 1) = _tmp171 * _tmp275 + _tmp172 * _tmp259 - _tmp172 * _tmp266 +
                            _tmp173 * _tmp260 + _tmp174 * _tmp267 - _tmp174 * _tmp273 +
                            _tmp175 * _tmp268 - _tmp176 * _tmp265 + _tmp176 * _tmp272 +
                            _tmp243 * _tmp274 - _tmp244 * _tmp269 - _tmp245 * _tmp270 -
                            _tmp246 * _tmp271;
    _new_covariance(3, 1) = _tmp171 * _tmp292 - _tmp172 * _tmp286 + _tmp172 * _tmp288 +
                            _tmp173 * _tmp287 - _tmp174 * _tmp281 + _tmp174 * _tmp282 +
                            _tmp175 * _tmp285 - _tmp176 * _tmp280 + _tmp176 * _tmp289 +
                            _tmp243 * _tmp283 - _tmp244 * _tmp284 - _tmp245 * _tmp290 -
                            _tmp246 * _tmp291;
    _new_covariance(4, 1) = _tmp171 * _tmp302 - _tmp172 * _tmp308 + _tmp172 * _tmp310 +
                            _tmp173 * _tmp311 - _tmp174 * _tmp303 + _tmp174 * _tmp304 +
                            _tmp175 * _tmp301 - _tmp176 * _tmp299 + _tmp176 * _tmp305 +
                            _tmp243 * _tmp309 - _tmp244 * _tmp300 - _tmp245 * _tmp307 -
                            _tmp246 * _tmp306;
    _new_covariance(5, 1) = _tmp171 * _tmp328 + _tmp172 * _tmp321 - _tmp172 * _tmp326 +
                            _tmp173 * _tmp318 - _tmp174 * _tmp317 + _tmp174 * _tmp320 +
                            _tmp175 * _tmp327 + _tmp176 * _tmp325 - _tmp176 * _tmp329 +
                            _tmp243 * _tmp319 - _tmp244 * _tmp322 - _tmp245 * _tmp323 -
                            _tmp246 * _tmp324;
    _new_covariance(6, 1) = _tmp171 * _tmp342 + _tmp172 * _tmp330 - _tmp172 * _tmp345 +
                            _tmp173 * _tmp348 - _tmp174 * _tmp339 + _tmp174 * _tmp344 +
                            _tmp175 * _tmp347 + _tmp176 * _tmp331 - _tmp176 * _tmp346 +
                            _tmp243 * _tmp338 - _tmp244 * _tmp343 - _tmp245 * _tmp340 -
                            _tmp246 * _tmp341;
    _new_covariance(0, 2) = _tmp181 * _tmp232 + _tmp182 * _tmp233 - _tmp182 * _tmp240 -
                            _tmp183 * _tmp234 + _tmp183 * _tmp237 + _tmp184 * _tmp236 +
                            _tmp185 * _tmp225 - _tmp185 * _tmp238 + _tmp186 * _tmp239 -
                            _tmp230 * _tmp261 - _tmp231 * _tmp262 - _tmp235 * _tmp263 +
                            _tmp241 * _tmp264;
    _new_covariance(1, 2) = _tmp181 * _tmp256 + _tmp182 * _tmp242 - _tmp182 * _tmp254 -
                            _tmp183 * _tmp247 + _tmp183 * _tmp248 + _tmp184 * _tmp258 +
                            _tmp185 * _tmp253 - _tmp185 * _tmp257 + _tmp186 * _tmp251 +
                            _tmp249 * _tmp264 - _tmp250 * _tmp263 - _tmp252 * _tmp261 -
                            _tmp255 * _tmp262;
    _new_covariance(2, 2) = _tmp181 * _tmp275 - _tmp182 * _tmp265 + _tmp182 * _tmp272 +
                            _tmp183 * _tmp267 - _tmp183 * _tmp273 + _tmp184 * _tmp268 +
                            _tmp185 * _tmp259 - _tmp185 * _tmp266 + _tmp186 * _tmp260 -
                            _tmp261 * _tmp269 - _tmp262 * _tmp274 - _tmp263 * _tmp271 +
                            _tmp264 * _tmp270;
    _new_covariance(3, 2) = _tmp181 * _tmp292 - _tmp182 * _tmp280 + _tmp182 * _tmp289 -
                            _tmp183 * _tmp281 + _tmp183 * _tmp282 + _tmp184 * _tmp285 -
                            _tmp185 * _tmp286 + _tmp185 * _tmp288 + _tmp186 * _tmp287 -
                            _tmp261 * _tmp284 - _tmp262 * _tmp283 - _tmp263 * _tmp291 +
                            _tmp264 * _tmp290;
    _new_covariance(4, 2) = _tmp181 * _tmp302 - _tmp182 * _tmp299 + _tmp182 * _tmp305 -
                            _tmp183 * _tmp303 + _tmp183 * _tmp304 + _tmp184 * _tmp301 -
                            _tmp185 * _tmp308 + _tmp185 * _tmp310 + _tmp186 * _tmp311 -
                            _tmp261 * _tmp300 - _tmp262 * _tmp309 - _tmp263 * _tmp306 +
                            _tmp264 * _tmp307;
    _new_covariance(5, 2) = _tmp181 * _tmp328 + _tmp182 * _tmp325 - _tmp182 * _tmp329 -
                            _tmp183 * _tmp317 + _tmp183 * _tmp320 + _tmp184 * _tmp327 +
                            _tmp185 * _tmp321 - _tmp185 * _tmp326 + _tmp186 * _tmp318 -
                            _tmp261 * _tmp322 - _tmp262 * _tmp319 - _tmp263 * _tmp324 +
                            _tmp264 * _tmp323;
    _new_covariance(6, 2) = _tmp181 * _tmp342 + _tmp182 * _tmp331 - _tmp182 * _tmp346 -
                            _tmp183 * _tmp339 + _tmp183 * _tmp344 + _tmp184 * _tmp347 +
                            _tmp185 * _tmp330 - _tmp185 * _tmp345 + _tmp186 * _tmp348 -
                            _tmp261 * _tmp343 - _tmp262 * _tmp338 - _tmp263 * _tmp341 +
                            _tmp264 * _tmp340;
    _new_covariance(0, 3) = -_tmp192 * _tmp234 + _tmp192 * _tmp237 + _tmp193 * _tmp239 +
                            _tmp194 * _tmp232 + _tmp195 * _tmp236 + _tmp196 * _tmp233 -
                            _tmp196 * _tmp240 + _tmp197 * _tmp225 - _tmp197 * _tmp238 -
                            _tmp230 * _tmp278 - _tmp231 * _tmp279 + _tmp235 * _tmp276 -
                            _tmp241 * _tmp277;
    _new_covariance(1, 3) = -_tmp192 * _tmp247 + _tmp192 * _tmp248 + _tmp193 * _tmp251 +
                            _tmp194 * _tmp256 + _tmp195 * _tmp258 + _tmp196 * _tmp242 -
                            _tmp196 * _tmp254 + _tmp197 * _tmp253 - _tmp197 * _tmp257 -
                            _tmp249 * _tmp277 + _tmp250 * _tmp276 - _tmp252 * _tmp278 -
                            _tmp255 * _tmp279;
    _new_covariance(2, 3) = _tmp192 * _tmp267 - _tmp192 * _tmp273 + _tmp193 * _tmp260 +
                            _tmp194 * _tmp275 + _tmp195 * _tmp268 - _tmp196 * _tmp265 +
                            _tmp196 * _tmp272 + _tmp197 * _tmp259 - _tmp197 * _tmp266 -
                            _tmp269 * _tmp278 - _tmp270 * _tmp277 + _tmp271 * _tmp276 -
                            _tmp274 * _tmp279;
    _new_covariance(3, 3) = -_tmp192 * _tmp281 + _tmp192 * _tmp282 + _tmp193 * _tmp287 +
                            _tmp194 * _tmp292 + _tmp195 * _tmp285 - _tmp196 * _tmp280 +
                            _tmp196 * _tmp289 - _tmp197 * _tmp286 + _tmp197 * _tmp288 +
                            _tmp276 * _tmp291 - _tmp277 * _tmp290 - _tmp278 * _tmp284 -
                            _tmp279 * _tmp283;
    _new_covariance(4, 3) = -_tmp192 * _tmp303 + _tmp192 * _tmp304 + _tmp193 * _tmp311 +
                            _tmp194 * _tmp302 + _tmp195 * _tmp301 - _tmp196 * _tmp299 +
                            _tmp196 * _tmp305 - _tmp197 * _tmp308 + _tmp197 * _tmp310 +
                            _tmp276 * _tmp306 - _tmp277 * _tmp307 - _tmp278 * _tmp300 -
                            _tmp279 * _tmp309;
    _new_covariance(5, 3) = -_tmp192 * _tmp317 + _tmp192 * _tmp320 + _tmp193 * _tmp318 +
                            _tmp194 * _tmp328 + _tmp195 * _tmp327 + _tmp196 * _tmp325 -
                            _tmp196 * _tmp329 + _tmp197 * _tmp321 - _tmp197 * _tmp326 +
                            _tmp276 * _tmp324 - _tmp277 * _tmp323 - _tmp278 * _tmp322 -
                            _tmp279 * _tmp319;
    _new_covariance(6, 3) = -_tmp192 * _tmp339 + _tmp192 * _tmp344 + _tmp193 * _tmp348 +
                            _tmp194 * _tmp342 + _tmp195 * _tmp347 + _tmp196 * _tmp331 -
                            _tmp196 * _tmp346 + _tmp197 * _tmp330 - _tmp197 * _tmp345 +
                            _tmp276 * _tmp341 - _tmp277 * _tmp340 - _tmp278 * _tmp343 -
                            _tmp279 * _tmp338;
    _new_covariance(0, 4) = _tmp202 * _tmp239 + _tmp203 * _tmp225 - _tmp203 * _tmp238 +
                            _tmp204 * _tmp236 + _tmp205 * _tmp233 + _tmp206 * _tmp232 -
                            _tmp207 * _tmp234 + _tmp207 * _tmp237 - _tmp230 * _tmp295 -
                            _tmp231 * _tmp294 - _tmp235 * _tmp297 + _tmp240 * _tmp298 -
                            _tmp241 * _tmp296;
    _new_covariance(1, 4) = _tmp202 * _tmp251 + _tmp203 * _tmp253 - _tmp203 * _tmp257 +
                            _tmp204 * _tmp258 + _tmp205 * _tmp242 + _tmp206 * _tmp256 -
                            _tmp207 * _tmp247 + _tmp207 * _tmp248 - _tmp249 * _tmp296 -
                            _tmp250 * _tmp297 - _tmp252 * _tmp295 + _tmp254 * _tmp298 -
                            _tmp255 * _tmp294;
    _new_covariance(2, 4) = _tmp202 * _tmp260 + _tmp203 * _tmp259 - _tmp203 * _tmp266 +
                            _tmp204 * _tmp268 + _tmp205 * _tmp272 + _tmp206 * _tmp275 +
                            _tmp207 * _tmp267 - _tmp207 * _tmp273 + _tmp265 * _tmp298 -
                            _tmp269 * _tmp295 - _tmp270 * _tmp296 - _tmp271 * _tmp297 -
                            _tmp274 * _tmp294;
    _new_covariance(3, 4) = _tmp202 * _tmp287 - _tmp203 * _tmp286 + _tmp203 * _tmp288 +
                            _tmp204 * _tmp285 + _tmp205 * _tmp289 + _tmp206 * _tmp292 -
                            _tmp207 * _tmp281 + _tmp207 * _tmp282 + _tmp280 * _tmp298 -
                            _tmp283 * _tmp294 - _tmp284 * _tmp295 - _tmp290 * _tmp296 -
                            _tmp291 * _tmp297;
    _new_covariance(4, 4) = _tmp202 * _tmp311 - _tmp203 * _tmp308 + _tmp203 * _tmp310 +
                            _tmp204 * _tmp301 + _tmp205 * _tmp305 + _tmp206 * _tmp302 -
                            _tmp207 * _tmp303 + _tmp207 * _tmp304 - _tmp294 * _tmp309 -
                            _tmp295 * _tmp300 - _tmp296 * _tmp307 - _tmp297 * _tmp306 +
                            _tmp298 * _tmp299;
    _new_covariance(5, 4) = _tmp202 * _tmp318 + _tmp203 * _tmp321 - _tmp203 * _tmp326 +
                            _tmp204 * _tmp327 + _tmp205 * _tmp325 + _tmp206 * _tmp328 -
                            _tmp207 * _tmp317 + _tmp207 * _tmp320 - _tmp294 * _tmp319 -
                            _tmp295 * _tmp322 - _tmp296 * _tmp323 - _tmp297 * _tmp324 +
                            _tmp298 * _tmp329;
    _new_covariance(6, 4) = _tmp202 * _tmp348 + _tmp203 * _tmp330 - _tmp203 * _tmp345 +
                            _tmp204 * _tmp347 + _tmp205 * _tmp331 + _tmp206 * _tmp342 -
                            _tmp207 * _tmp339 + _tmp207 * _tmp344 - _tmp294 * _tmp338 -
                            _tmp295 * _tmp343 - _tmp296 * _tmp340 - _tmp297 * _tmp341 +
                            _tmp298 * _tmp346;
    _new_covariance(0, 5) = -_tmp210 * _tmp234 + _tmp210 * _tmp237 + _tmp212 * _tmp232 +
                            _tmp213 * _tmp225 + _tmp214 * _tmp233 - _tmp214 * _tmp240 +
                            _tmp215 * _tmp239 + _tmp216 * _tmp236 - _tmp230 * _tmp315 -
                            _tmp231 * _tmp316 - _tmp235 * _tmp312 + _tmp238 * _tmp314 -
                            _tmp241 * _tmp313;
    _new_covariance(1, 5) = -_tmp210 * _tmp247 + _tmp210 * _tmp248 + _tmp212 * _tmp256 +
                            _tmp213 * _tmp253 + _tmp214 * _tmp242 - _tmp214 * _tmp254 +
                            _tmp215 * _tmp251 + _tmp216 * _tmp258 - _tmp249 * _tmp313 -
                            _tmp250 * _tmp312 - _tmp252 * _tmp315 - _tmp255 * _tmp316 +
                            _tmp257 * _tmp314;
    _new_covariance(2, 5) = _tmp210 * _tmp267 - _tmp210 * _tmp273 + _tmp212 * _tmp275 +
                            _tmp213 * _tmp259 - _tmp214 * _tmp265 + _tmp214 * _tmp272 +
                            _tmp215 * _tmp260 + _tmp216 * _tmp268 + _tmp266 * _tmp314 -
                            _tmp269 * _tmp315 - _tmp270 * _tmp313 - _tmp271 * _tmp312 -
                            _tmp274 * _tmp316;
    _new_covariance(3, 5) = -_tmp210 * _tmp281 + _tmp210 * _tmp282 + _tmp212 * _tmp292 +
                            _tmp213 * _tmp288 - _tmp214 * _tmp280 + _tmp214 * _tmp289 +
                            _tmp215 * _tmp287 + _tmp216 * _tmp285 - _tmp283 * _tmp316 -
                            _tmp284 * _tmp315 + _tmp286 * _tmp314 - _tmp290 * _tmp313 -
                            _tmp291 * _tmp312;
    _new_covariance(4, 5) = -_tmp210 * _tmp303 + _tmp210 * _tmp304 + _tmp212 * _tmp302 +
                            _tmp213 * _tmp310 - _tmp214 * _tmp299 + _tmp214 * _tmp305 +
                            _tmp215 * _tmp311 + _tmp216 * _tmp301 - _tmp300 * _tmp315 -
                            _tmp306 * _tmp312 - _tmp307 * _tmp313 + _tmp308 * _tmp314 -
                            _tmp309 * _tmp316;
    _new_covariance(5, 5) = -_tmp210 * _tmp317 + _tmp210 * _tmp320 + _tmp212 * _tmp328 +
                            _tmp213 * _tmp321 + _tmp214 * _tmp325 - _tmp214 * _tmp329 +
                            _tmp215 * _tmp318 + _tmp216 * _tmp327 - _tmp312 * _tmp324 -
                            _tmp313 * _tmp323 + _tmp314 * _tmp326 - _tmp315 * _tmp322 -
                            _tmp316 * _tmp319;
    _new_covariance(6, 5) = -_tmp210 * _tmp339 + _tmp210 * _tmp344 + _tmp212 * _tmp342 +
                            _tmp213 * _tmp330 + _tmp214 * _tmp331 - _tmp214 * _tmp346 +
                            _tmp215 * _tmp348 + _tmp216 * _tmp347 - _tmp312 * _tmp341 -
                            _tmp313 * _tmp340 + _tmp314 * _tmp345 - _tmp315 * _tmp343 -
                            _tmp316 * _tmp338;
    _new_covariance(0, 6) = _tmp219 * _tmp225 - _tmp219 * _tmp238 + _tmp220 * _tmp239 +
                            _tmp221 * _tmp232 + _tmp222 * _tmp233 - _tmp222 * _tmp240 +
                            _tmp223 * _tmp236 + _tmp224 * _tmp237 - _tmp230 * _tmp336 -
                            _tmp231 * _tmp335 + _tmp234 * _tmp337 - _tmp235 * _tmp334 -
                            _tmp241 * _tmp333;
    _new_covariance(1, 6) = _tmp219 * _tmp253 - _tmp219 * _tmp257 + _tmp220 * _tmp251 +
                            _tmp221 * _tmp256 + _tmp222 * _tmp242 - _tmp222 * _tmp254 +
                            _tmp223 * _tmp258 + _tmp224 * _tmp248 + _tmp247 * _tmp337 -
                            _tmp249 * _tmp333 - _tmp250 * _tmp334 - _tmp252 * _tmp336 -
                            _tmp255 * _tmp335;
    _new_covariance(2, 6) = _tmp219 * _tmp259 - _tmp219 * _tmp266 + _tmp220 * _tmp260 +
                            _tmp221 * _tmp275 - _tmp222 * _tmp265 + _tmp222 * _tmp272 +
                            _tmp223 * _tmp268 + _tmp224 * _tmp267 - _tmp269 * _tmp336 -
                            _tmp270 * _tmp333 - _tmp271 * _tmp334 + _tmp273 * _tmp337 -
                            _tmp274 * _tmp335;
    _new_covariance(3, 6) = -_tmp219 * _tmp286 + _tmp219 * _tmp288 + _tmp220 * _tmp287 +
                            _tmp221 * _tmp292 - _tmp222 * _tmp280 + _tmp222 * _tmp289 +
                            _tmp223 * _tmp285 + _tmp224 * _tmp282 + _tmp281 * _tmp337 -
                            _tmp283 * _tmp335 - _tmp284 * _tmp336 - _tmp290 * _tmp333 -
                            _tmp291 * _tmp334;
    _new_covariance(4, 6) = -_tmp219 * _tmp308 + _tmp219 * _tmp310 + _tmp220 * _tmp311 +
                            _tmp221 * _tmp302 - _tmp222 * _tmp299 + _tmp222 * _tmp305 +
                            _tmp223 * _tmp301 + _tmp224 * _tmp304 - _tmp300 * _tmp336 +
                            _tmp303 * _tmp337 - _tmp306 * _tmp334 - _tmp307 * _tmp333 -
                            _tmp309 * _tmp335;
    _new_covariance(5, 6) = _tmp219 * _tmp321 - _tmp219 * _tmp326 + _tmp220 * _tmp318 +
                            _tmp221 * _tmp328 + _tmp222 * _tmp325 - _tmp222 * _tmp329 +
                            _tmp223 * _tmp327 + _tmp224 * _tmp320 + _tmp317 * _tmp337 -
                            _tmp319 * _tmp335 - _tmp322 * _tmp336 - _tmp323 * _tmp333 -
                            _tmp324 * _tmp334;
    _new_covariance(6, 6) = _tmp219 * _tmp330 - _tmp219 * _tmp345 + _tmp220 * _tmp348 +
                            _tmp221 * _tmp342 + _tmp222 * _tmp331 - _tmp222 * _tmp346 +
                            _tmp223 * _tmp347 + _tmp224 * _tmp344 - _tmp333 * _tmp340 -
                            _tmp334 * _tmp341 - _tmp335 * _tmp338 - _tmp336 * _tmp343 +
                            _tmp337 * _tmp339;
  }
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
